.scss-lint.yml
.travis.yml
Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/users/show.html.erb

I also added `scss-lint` onto the travis build.

Add a little bit of visual styling to the application template

---

app/views/organizations/new.html.erb

Show blankslate if the user doesn't have any orgs

---

app/views/users/show.html.erb

Make adding an organization front and center

---

app/controllers/assignments_controller.rb
app/models/assignment.rb
app/models/organization.rb
app/views/assignments/_delete_assignment_modal.html.erb
app/views/assignments/edit.html.erb
app/views/assignments/new.html.erb
app/views/assignments/show.html.erb
app/views/invitations/_invitation.html.erb
app/views/organizations/show.html.erb
config/application.rb
config/routes.rb
db/migrate/20150602155858_create_assignments.rb
db/schema.rb
test/controllers/assignments_controller_test.rb
test/factories.rb

I'm trying to break this process into more PRs, this one just allows the basic crud actions on an assignment with a UI.

Created starter template for assignments

---

app/views/organizations/show.html.erb
app/views/users/show.html.erb

Update the copy on the organizations blankslate, and add a blank slate to assignments
Fixes #45 and #44
/cc @johndbritton 
This is the new assignments blankslate

Blankslates

---

config/environments/production.rb

That way I'll stop getting URI redirect mismatches

Force SSL on Production

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.coffee
app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
config/application.rb
config/environments/production.rb
config/initializers/peek.rb
config/routes.rb
db/migrate/20150720170719_add_site_admin_to_user.rb
db/schema.rb
spec/models/user_spec.rb

Add Peek status bar to Classroom

---

Gemfile
Gemfile.lock
app/controllers/assignments_controller.rb
app/controllers/group_assignments_controller.rb
app/helpers/invitations_helper.rb
app/models/assignment.rb
app/models/group_assignment.rb
app/models/organization.rb
app/views/assignment_invitations/_assignment_invitation.html.erb
app/views/group_assignment_invitations/_group_assignment_invitation.html.erb
config/initializers/bitly.rb
config/routes.rb
db/migrate/20150809162441_add_slugs.rb
db/schema.rb
spec/models/organization_spec.rb

This makes the apps url more user friendly, creating slugs out of the titles for
* `Organization`
* `Assignment`
* `GroupAssignment`
This also sets up the `bit.ly` API so that in production the invitations urls are much more readable.

Friendlier URLs

---

app/controllers/application_controller.rb
app/controllers/assignments_controller.rb
app/controllers/group_assignments_controller.rb
app/controllers/invitations_controller.rb
app/controllers/organizations_controller.rb
app/controllers/pages_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb

Opt out of being logged as opposed to opting in

---

app/controllers/sessions_controller.rb
app/views/shared/_header.html.erb
config/routes.rb

Change logout route to be post

---

Gemfile
Gemfile.lock
config.ru

Also remove the bitly gem due to the fact I missed it before
To set this up on production
```
heroku config:add CANONICAL_HOST=classroom.github.com
```

Add rack-canonical-host

---

Gemfile
Gemfile.lock
app/controllers/organizations_controller.rb
app/controllers/users_controller.rb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/organizations/show.html.erb
app/views/users/show.html.erb
config/initializers/kaminari_config.rb
config/locales/en.yml

Right now this will be on the users organizations at `/dashboard`, and organizations assignments listing.
Needs styling, that can happen in #101 

Add Pagination

---

config/initializers/octokit.rb

Set shared cache to be false

---

config/routes.rb

orgs -> organizations

---

Gemfile
Gemfile.lock
app/decorators/organization_decorator.rb
app/views/organizations/_organization_banner.html.erb

Use geo_pattern on the organization banner

---

app/views/assignment_repos/_assignment_repo.html.erb
app/views/group_assignment_repos/_group_assignment_repo.html.erb

Actually link to the GitHub repos

---

app/views/organizations/edit.html.erb

Closes #136 
Forms cannot be in other forms :cry: 

Fix organization settings form

---

Gemfile
Gemfile.lock
app/views/peek/views/_sidekiq.html.erb
app/views/shared/_header.html.erb
app/views/shared/_staff_links.html.erb
config/initializers/peek.rb
config/routes.rb

Closes #123 
This adds sidekiq-peek to the top bar, and adds the link so that you can go to the webpath from the bar as well.
/cc @johndbritton for review

Add sidekiq-peek to the status bar with link to the web path

---

app/assets/stylesheets/components/flash.scss
app/views/shared/_error_messages.html.erb
app/views/shared/_flash_messages.html.erb

Fix formatting for flash messages

---

app/views/organizations/new_assignment.html.erb

Replace placeholder copy for assignments

---

app/assets/javascripts/flash-messages.coffee

Fix flash message removal

---

app/decorators/organization_decorator.rb

Keep the header consistent if the name changes by using the github_id

---

app/assets/javascripts/application.coffee
app/assets/javascripts/buttons.coffee
app/assets/javascripts/navigation.coffee
app/assets/stylesheets/components/loading-indicator.scss
app/views/assignment_invitations/show.html.erb
app/views/assignments/_assignment.html.erb
app/views/assignments/edit.html.erb
app/views/assignments/show.html.erb
app/views/group_assignment_invitations/accept.html.erb
app/views/group_assignment_invitations/show.html.erb
app/views/group_assignments/edit.html.erb
app/views/layouts/application.html.erb
app/views/layouts/invitations.html.erb

Fix double confirm and add loading indicator for multiple pages.

---

app/views/group_assignment_invitations/show.html.erb

Warn the users that they cannot change teams on classroom

---

app/assets/stylesheets/layout.scss
app/decorators/organization_decorator.rb
app/views/organizations/_organization.html.erb

Organization Listing Styling

---

app/views/group_assignments/_group_assignment_form_options.html.erb

We do this for Assignments but not for Group Assignments

Add starter code name placeholder for group assignments

---

app/views/shared/_header.html.erb

Serves me right for showing up here and trying to actually do something. I'll stick to commentary from now on @tarebyte.

Query strings begin with `?`

---

app/assets/javascripts/zeroclipboard.coffee
app/views/assignment_invitations/_assignment_invitation.html.erb
app/views/assignments/_assignment.html.erb
app/views/group_assignment_invitations/_group_assignment_invitation.html.erb
app/views/group_assignments/_group_assignment.html.erb
app/views/organizations/_invite_users.html.erb

Fixes #194 
Since I wasn't making the buttons unique with an id, it just copied the first one by default no matter what.

Make zeroclipboard buttons unique for copying

---

app/views/group_assignments/_group_assignment_form_options.html.erb

Give a helpful name for the reusable set of teams

---

app/views/organizations/_organization.html.erb

Add @ to organization login

---

app/assets/stylesheets/components/buttons.scss
app/views/pages/home.html.erb

Match blue button style from education.github.com

---

app/assets/stylesheets/components/buttons.scss
app/assets/stylesheets/grid-system.scss
app/assets/stylesheets/layout.scss
app/views/pages/home.html.erb

Just fixing up some styling issue I noticed.

Front page fixup

---

.travis.yml

Turn off travis ci build notifications

---

app/assets/stylesheets/components/buttons.scss
app/views/pages/home.html.erb
app/views/shared/_invitation_header.html.erb

Just some things I found, styling wise

Mobile again

---

app/views/assignments/show.html.erb
app/views/group_assignments/show.html.erb
app/views/organizations/index.html.erb
app/views/organizations/show.html.erb
app/views/shared/_pagination.html.erb

I also missed the organization view
This will only put in the partial if there are multiple pages of pagination. That way we don't get weird padding errors.

Extract pagination view

---

app/models/organization.rb
db/migrate/20150922104925_remove_uniqueness_of_organization_title.rb
db/schema.rb

Also remove the uniqueness of the title on the DB

Use the github_id as part of the slug

---

app/views/peek/views/_sidekiq.html.erb

Remove total count from sidekiq view on the peek bar

---

README.md

Otherwise people can't run background jobs

Mention using sidekiq in another terminal window

---

app/assets/stylesheets/components/protip.scss
app/views/organizations/new.html.erb

Add ProTip to remind users to grant the app access to the org

---

app/views/organizations/new.html.erb

Make the link in the ProTip open in a new window.

Open application access in new window

---

app/views/organizations/new.html.erb

Target is last

---

script/setup

Remove --no-clobber replace with -n

---

.gitignore

Add `rdb.dump` to `.gitignore`

Ignore rdb.dump

---

Gemfile
Gemfile.lock

Update gems, remove sha lock from Octokit

---

app/views/shared/_footer.html.erb

I thought i'd submit the PR, this is related to [issue#296 ](https://github.com/education/classroom/issues/296). I added an additional line in `shared/_footer.html.erb` to render the note requested.

Added note stating project is open source with link to repo

---

app/views/layouts/application.html.erb

This pull request closes #249, adding the open graph metadata as sugested by @tjhorner

Add open graph metadata

---

app/views/layouts/application.html.erb
app/views/layouts/invitations.html.erb
app/views/layouts/pages.html.erb
app/views/shared/_open_graph.html.erb

This is a follow up to #303 which moves the opengraph data to a partial and renders the partial in all layouts.
cc/ #249

Render open graph info in all layouts

---

app/views/organizations/_invite_users.html.erb
app/views/organizations/_reset_and_remove_organization_modal.html.erb
app/views/organizations/edit.html.erb
app/views/organizations/index.html.erb
app/views/organizations/new.html.erb
config/routes.rb

This is to help clarify for users the difference between a GitHub organization and a Classroom on Classroom for GitHub.
Closes #250, closes #252 
/cc @johndbritton for opinions and copy

Clarify the difference between Organization and Classroom (WIP)

---

app/models/null_git_hub_user.rb

Fixes #329 
/cc @johndbritton 
we definitely need tests for these at some point.

fix NoMethodError for NullGitHubUser

---

app/assets/javascripts/application.coffee
app/assets/javascripts/outline-box.coffee
app/assets/stylesheets/components/outline-box.scss
app/views/group_assignments/_permission_info_box.html.erb
app/views/group_assignments/show.html.erb
vendor/assets/bower.json
vendor/assets/bower_components/js-cookie/.bower.json
vendor/assets/bower_components/js-cookie/CONTRIBUTING.md
vendor/assets/bower_components/js-cookie/MIT-LICENSE.txt
vendor/assets/bower_components/js-cookie/README.md
vendor/assets/bower_components/js-cookie/bower.json
vendor/assets/bower_components/js-cookie/src/js.cookie.js

Add info box to alert users to change their permissions

---

app/controllers/organizations_controller.rb

Closes #346
/cc @johndbritton @carnevlu

Check for presence of name for Classroom creation

---

spec/lib/staff_constraint_spec.rb

... to increase overall test coverage a bit ;)

adding test for staff_constraint.rb

---

Gemfile
Gemfile.lock
config/initializers/puma_worker_killer.rb

Closes #385 
/cc @mkcode @johndbritton

Add puma_worker_killer to Classroom

---

spec/lib/staff_constraint_spec.rb

addressing https://github.com/education/classroom/pull/384#discussion_r46772702 it block preference

changing short it block version to do end version

---

app/views/assignments/_delete_assignment_modal.html.erb
app/views/group_assignments/_delete_group_assignment_modal.html.erb
app/views/organizations/_reset_and_remove_organization_modal.html.erb

Closes #396 autofocus user input textbox

---

app/controllers/stafftools/assignment_invitations_controller.rb
app/controllers/stafftools/assignment_repos_controller.rb
app/controllers/stafftools/assignments_controller.rb
app/controllers/stafftools/group_assignment_invitations_controller.rb
app/controllers/stafftools/group_assignment_repos_controller.rb
app/controllers/stafftools/group_assignments_controller.rb
app/controllers/stafftools/groupings_controller.rb
app/controllers/stafftools/groups_controller.rb
app/controllers/stafftools/organizations_controller.rb
app/controllers/stafftools/repo_accesses_controller.rb
app/controllers/stafftools/users_controller.rb

Raise 404 when we can't find the resource in stafftools

---

README.md

Fixing a tiny typo.

---

config/chewy.rb

Reverts education/classroom#425
This didn't help, so reverting.

Revert "Set Chewy to log level info"

---

app/controllers/assignments_controller.rb
app/controllers/group_assignments_controller.rb

These lookups should be scoped to the active organization.

Scope assignment lookup to organization

---

config/chewy.rb
config/initializers/chewy.rb

Set chewy to log level info in production

---

Gemfile.lock
config/application.rb
config/environments/production.rb

Will close #426 once we get it sorted out.
I just took a quick stab at debugging it, updated `dalli` and set the `config.cache_store = :dalli_store`

Reconfigure Dalli

---

config/application.rb

Check memcahed connection correctly

---

README.md

the rbenv install command use version 2.3.0 but the text says 2.2.4

ruby version updated

---

Gemfile.lock
app/assets/stylesheets/components/peek.scss
app/assets/stylesheets/components/stafftools.scss
app/views/peek/_bar.html.erb

Just made a few aesthetic updates to the peek bar.

Peek updates

---

Gemfile
Procfile.dev
config/initializers/puma_worker_killer.rb

Small server changes to make dev life better

Server changes

---

app/models/git_hub_repository.rb

Closes #489 
This needs to have tests, but I'd like to follow up with that when I have more time.
/cc @johndbritton @crichID

Add credentials to source_import request

---

README.md

Updated the Getting started guide in order to be more user friendly and allow people to get setup and start contributing quicker.

Getting started clarity

---

app/assets/javascripts/navigation.coffee

Hi guys,
This is a fix to #442.
Any feedback would be greatly appreciated.
Thanks! :smile:

[fix] Hide Octospinner when opening in a new tab/new window.

---

Gemfile
Gemfile.lock
README.md
app.json
config/initializers/airbrake.rb
config/initializers/timeout.rb

This was recommended by @mkcode as something that would be useful for Classroom to have.
/cc @johndbritton @mkcode

Update Airbrake, and Introduce Rack Timeouts

---

app/views/assignments/show.html.erb
app/views/group_assignments/show.html.erb
app/views/organizations/_organization_banner.html.erb

Closes #513 
/cc @jasonlong @johndbritton

Settings buttons look too similar

---

README.md

To encourage contributors to help out.
cc/ @tarebyte

Link to help-wanted issues from the readme

---

app/views/stafftools/assignments/show.html.erb
app/views/stafftools/group_assignment_repos/show.html.erb
app/views/stafftools/group_assignments/show.html.erb
app/views/stafftools/groupings/show.html.erb
app/views/stafftools/groups/show.html.erb
app/views/stafftools/organizations/show.html.erb
app/views/stafftools/repo_accesses/show.html.erb

trying to debug information and I found missing pieces of information I needed.

Add missing information

---

README.md

Changed the project name on the top left corner from `Classroom for GitHub` to `GitHub Classroom`.
Thanks

Update name in README.md screenshot

---

config/initializers/timeout.rb

Use the correct name for the rack-timeout fixes in #590.

get the gem right this time

---

README.md

Update Ruby version to `2.3.1` in `README.md`.
I also tried to update the `rubocop`, but I think it will be updated in  #585.

Update Ruby version in README.md

---

app/controllers/assignments_controller.rb
app/controllers/group_assignments_controller.rb
app/controllers/organizations_controller.rb
app/controllers/stafftools/organizations_controller.rb
app/models/organization.rb
app/services/auth_hash.rb
config/initializers/airbrake.rb
spec/support/vcr.rb

I ran [bullet](https://github.com/flyerhzm/bullet) and [fasterer](https://github.com/DamirSvrtan/fasterer) on the project.
Not too bad.

Fix N+1 issues and small speed optimizations

---

db/migrate/20160612130650_add_nonnullity_constraint_to_last_active_at.rb
db/schema.rb

[Migration] Ensure that last_active_at can't be null

---

app/decorators/group_assignment_decorator.rb
app/decorators/group_assignment_repo_decorator.rb

This a fix for the original bug reported in #637

Fix GroupAssignmentRepo decorator

---

app/models/null_github_organization.rb

Fixes https://github-education.airbrake.io/projects/116727/groups/1709076646104891071

Add null user id to NullOrganization

---

app/views/autocomplete/_repository_suggestions.html.erb

Closes https://github-education.airbrake.io/projects/116727/groups/1714557334048436580
/cc @dinever

Fix octicon syntax for repo autocomplete

---

app/jobs/application_job.rb
app/jobs/destroy_resource_job.rb
app/models/application_record.rb
app/models/assignment.rb
app/models/assignment_invitation.rb
app/models/assignment_repo.rb
app/models/group.rb
app/models/group_assignment.rb
app/models/group_assignment_invitation.rb
app/models/group_assignment_repo.rb
app/models/grouping.rb
app/models/organization.rb
app/models/repo_access.rb
app/models/student_identifier.rb
app/models/student_identifier_type.rb
app/models/user.rb

[Moving to Rails 5](https://github.com/education/classroom/pull/663) is a pretty big PR.
I'm trying to move over what I can to break up the changes into small bits.
/cc @johndbritton @dinever @cyhsutw @mkcode

Move models and jobs to inherit from ApplicationRecord or ApplicationBase

---

config/application.rb

Didn't see the correlation between me getting paged and the issue at hand.

Fix pinglish elasticsearch

---

app/controllers/application_controller.rb
app/controllers/assignment_invitations_controller.rb
app/controllers/group_assignment_invitations_controller.rb
lib/github/errors.rb

Looks like we're missing an `r`.

[Minor] Fix typos

---

Brewfile

Add java for elasticsearch

---

app/views/shared/_header.html.erb
app/views/shared/_invitation_header.html.erb

Link to GitHub Education Community

---

app/controllers/sessions_controller.rb
app/views/layouts/pages.html.erb
spec/integration/authentication_spec.rb

Set explicit failure message for authentication failure

---

app/controllers/group_assignment_invitations_controller.rb
app/views/group_assignment_invitations/_group_assignment_team.erb

Closes #724 
On production this site is timing out because we are loading all of the resources on the invitation page.

Limit number of students listed on invitation page

---

app/views/pages/home.html.erb
config/locales/views/pages/en.yml

PR to add i18n strings to pages views.
#662

Add i18n strings for home page

---

Gemfile
Gemfile.lock
app/views/shared/_footer.html.erb
config/application.rb
config/locales/views/shared/en.yml

Hi @tarebyte, I've removed the test and carybara.
Thank you for your input!

I18n setup + shared/footer I18n

---

app/views/stafftools/assignment_repos/show.html.erb
app/views/stafftools/group_assignment_repos/show.html.erb

Move github information to it's own box

---

app/view_models/view_model.rb
spec/view_models/view_model_spec.rb

This is the design pattern I want to move forward with, we should move view logic into `ViewModel`s to make it testable.
This adds `ViewModel` super class with specs.

Add ViewModels to Classroom

---

app/controllers/videos_controller.rb
app/view_models/video/show_view.rb
app/views/shared/_header.html.erb
app/views/shared/_invitation_header.html.erb
app/views/videos/index.html.erb
config/initializers/videos.rb
config/locales/views/shared/en.yml
config/routes.rb
config/videos.yml
spec/controllers/videos_controller_spec.rb
spec/view_models/video/show_view_spec.rb

Per request of @sanicki this adds the Classroom tutorial videos to the app.
/cc @johndbritton for feedback
/cc @jasonlong for 🎨 critique

Add tutorial videos to Classroom

---

config/videos.yml

Fix last video id

---

app/views/stafftools/organizations/show.html.erb

Add more Stafftools context for Organizations

---

Gemfile
Gemfile.lock

Upgrade Sidekiq

---

Gemfile
Gemfile.lock
config/initializers/octokit.rb

This adds the [Typheous](https://github.com/typhoeus/typhoeus) gem so that we can run HTTP requests to the GitHub API in parallel

Use Typhoeus as adapter for Octokit

---

Gemfile
Gemfile.lock
Procfile.dev
app/assets/javascripts/application.js
config/environments/development.rb

This should also finally remove all of the deprecation warnings

Minor updates

---

app/views/assignments/_assignment.html.erb
app/views/assignments/show.html.erb
app/views/stafftools/assignment_invitations/show.html.erb
app/views/stafftools/assignment_repos/show.html.erb
app/views/stafftools/assignments/show.html.erb
app/views/stafftools/group_assignment_invitations/show.html.erb
app/views/stafftools/group_assignment_repos/show.html.erb
app/views/stafftools/group_assignments/show.html.erb

Change assigment to assignment

---

Gemfile
Gemfile.lock

Update peek-dalli to remove atomic dep

---

.rubocop.yml
app/models/assignment_invitation.rb
app/models/group_assignment_invitation.rb
app/models/user.rb

Not sure why I ever disabled this...

Enable Rails delegate cop

---

public/422.html
public/500.html

Update 500 & 422 error pages
`500`
`422`

Update rest of error pages

---

app/assets/javascripts/identifier-form.js

Fixes our currently borked Javascript while I work on the webpacker transition
/cc @nwoodthorpe

Verify the student identifier form value is defined

---

app/assets/javascripts/organization-invite.js

It's breaking all of the forms

Disable organization invite JS

---

db/migrate/20170609181547_create_deadlines_table.rb
db/migrate/20170609181708_add_submission_sha_to_assignment_repos.rb
db/schema.rb

Part 1/2
This PR introduces the migrations necessary for the deadlines PR.

Migrations for deadlines PR

---

Procfile.dev

Specify port 5000 for running dev server (#914)

Enforce port 5000

---

app/models/assignment_repo/creator.rb
app/models/concerns/github_plan.rb
app/models/organization.rb
app/view_models/form_view.rb
app/views/assignments/_assignment_form_options.html.erb
app/views/group_assignments/_group_assignment_form_options.html.erb

Reverts education/classroom#924

Revert "Private repos"

---

app/views/stafftools/_navigation.html.erb
app/views/stafftools/group_assignments/show.html.erb

- Add selected class to search link only on stafftools_root page
- Fix grouping link in stafftools/group_assignment

UI improvement and Link Fix in stafftools

---

app/models/organization.rb
app/models/roster.rb
app/models/roster_entry.rb
spec/factories.rb
spec/models/roster_entry_spec.rb
spec/models/roster_spec.rb

Closes #986 
Models for rosters: https://github.com/education/classroom/issues/448#issuecomment-311786419
Based on #984 so until that's merged, the diff will look weird. The last 2 commits are from this PR.

Models for rosters

---

app/views/stafftools/assignment_repos/_assignment_repo.html.erb
app/views/stafftools/assignment_repos/show.html.erb
config/locales/views/stafftools/assignment_repos/en.yml

Convert static text to symbol for stafftools/assignment_repos views

Add I18n support stafftools/assignment_repos

---

README.md

Closes https://github.com/education/classroom/issues/1039

Remove Dependency CI

---

config/initializers/statsd.rb

The time's we're getting with the current way of calculating total_time are extremely low. It seems like summing db_time and view_time gives a much more realistic total time.

New way of calculating time

---

app/controllers/application_controller/authentication_dependency.rb
config/initializers/scopes.rb
lib/github/token.rb
spec/lib/github/token_spec.rb

We had some weird stuff happening with scopes and child scopes.
This builds a scope tree and collects all of the scopes including the parent for comparison.

Fix scopes for Authing

---

app/controllers/application_controller.rb
app/controllers/organizations/controller.rb
app/controllers/organizations_controller.rb
app/views/assignments/_assignment.html.erb
app/views/group_assignments/_group_assignment.html.erb
app/views/organizations/_grouping.html.erb
app/views/organizations/_invite_users.html.erb
app/views/organizations/_organization_banner.html.erb
app/views/organizations/_reset_and_remove_organization_modal.html.erb
app/views/organizations/_side_menu.html.erb
app/views/organizations/edit.html.erb
app/views/organizations/new_assignment.html.erb
app/views/organizations/setup.html.erb
app/views/organizations/show.html.erb
app/views/organizations/show_groupings.html.erb
spec/controllers/organizations_controller_spec.rb

This will replace the `OrganizationAuthorization` concern.
Instead of ensuring that we include a concern I'm going to enforce the levels of authorization by changing the directory structure of the controllers.
Since this diff is rather large, I'm making these changes in tiny bits.

Add Organizations::Controller

---

app/views/organizations/_side_menu.html.erb

Missed this because I didn't have the feature flipping on right.

Fix side menu for rosters

---

.travis.yml

This sends our CI builds to our GitHub Slack channel 😄

Send notifications to GitHub slack channel

---

CODEOWNERS

Changing my old handle to my new handle in CODEOWNERS

Change nwoodthorpe to d12 in codeowners

---

README.md

Thanks @BenEmdon !
https://github.com/education/classroom/pull/1196#issuecomment-343350050

'nwoodthorpe' => 'd12' in README.md

---

README.md
lib/tasks/enable_features.rake

Hi there !
So I'm trying to understand Classroom's code better and to achieve that I created a basic rake task that enables all features for staff users.
I'm not sure with the right way to do it, especially for the users.
Also do the rake task need to be run during the `./script/server` script or do we just add it into the README ?
Thanks for your help !

Features rake task

---

app/views/orgs/rosters/new.html.erb

Hi there ! 👋 
I found a bad user experience while creating a roster.
The form validation is in server side, so if the user did not fill one field out of the two required, all data is lost (as the page reloads after hitting the submit button).
It can be solved by just adding `required: true` into the HTML but we lose the custom error messages. The data will be sent to the controller only if both fields aren't empty.
In order to keep those error messages we can add some JS but I don't know if it's a good thing to do.
Does someone have a thought about it ? 🤔 
Thanks a lot ! 🙇

Roster form validation

---

script/bootstrap

I got tired of running `./script/bootstrap` and it running installs instead of checking to make sure everything is good to go instead.

Make bootstrap script faster with checks

---

config/database.yml

I realized the other day that this was statically set.

Set the pool by using the RAILS_THREADS ENV

---

.rubocop.yml
config/application.rb
config/database.yml
config/environments/staging.rb

The names are a little out of sync, changing this to `classroom` instead of `github-classroom`

Update Faibot name to match our internal tooling

---

script/server
script/setup
script/update

Related to #1301 
After pairing with @d12 it appears that he had trouble to run the scripts as well so after digging a bit I tried to find a solution for both scripts.
**script/server**: we check if there is any existing containers, we stop them so we can restart them properly with the script.
**script/setup**: what happens is that we try to access the database when it's not ready yet. It solves everything by just waiting for the containers to be ready but I admit that it's not a pretty fix 🙈
#
cc @tarebyte as you worked, any suggestions would help me a lot (also this is a first version that I will improve 😤)
@d12 @damaneice @talsafran If you have time next week to try it on your end that would be awesome 🙏

script/setup and script/server fix

---

README.md

Update README docs link

---

README.md

Reverts education/classroom#1334 🙈

Revert "Update README docs link"

---

db/migrate/20180223160042_add_inivitation_enabled_to_assignment.rb
db/migrate/20180223161920_add_invitations_enabled_to_group_assignments.rb
db/schema.rb

Migration from https://github.com/education/classroom/pull/1290
CC @tarebyte

Invitations enabled migrations

---

CODEOWNERS

I'm not really active on this project anymore 😢 
While I'm happy to help out if folks need guidance, I probably don't need to be pinged on every new Pull Request.

Remove @tarebyte from CODEOWNERS file

---

app/assets/stylesheets/layout.scss
app/views/orgs/rosters/_download_csv_modal.html.erb

Adds scrolling to @ashleytqy 's work in #1379.

Add scrolling

---

db/migrate/20180711185234_add_status_to_assignment_invitation.rb
db/schema.rb

* Added a status:integer column to assignment_invitation
* Bumped schema
Part of #1385. Requested in to be separated out in https://github.com/education/classroom/pull/1385#discussion_r201724199
When this merges I will remove this patch from #1385

Add status column to assignment_invitation

---

app/assets/javascripts/setupv2.js

Add null check

---

app/views/assignment_invitations/setupv2.html.erb

This PR  proposes changes to the title at the top of `#setupv2`.
```diff
+ Your assignment repository is being setup. 
- Please wait for repository setup to finish. Do not leave this page.
``` 
Closes #1421

Changed #setupv2 title

---

app/controllers/application_controller/feature_flags_dependency.rb

This PR proposes a new feature flag for group import resiliency development.
Closes #1484

Add new feature flag for group import resiliency

---

app/jobs/assignment_repo/porter_status_job.rb
app/models/github_repository/import_dependency.rb

This PR moves a list from one class to another class. This way we can use the _list of steps_ in more places (like the upcoming porter status job).

Move the import steps list to shared component

---

app/jobs/assignment_repo/create_github_repository_job.rb

This PR proposes a cleanup of [`app/jobs/assignment_repo/create_github_repository_job.rb`](
https://github.com/education/classroom/blob/master/app/jobs/assignment_repo/create_github_repository_job.rb)
This PR Doesn't change any functionality but rather cleans up the current implementation into multiple methods (instead of one giant 💩).

Reduced Percieved and Cyclomatic Complecity

---

app/jobs/organization_event_job.rb
spec/jobs/organization_event_job_spec.rb

Nil check in organization_event_job.rb

---

app/models/assignment.rb
app/models/assignment_invitation.rb
app/models/assignment_repo.rb
app/models/group.rb
app/models/group_assignment.rb
app/models/group_assignment_invitation.rb
app/models/group_assignment_repo.rb
app/models/grouping.rb
app/models/organization.rb
app/models/repo_access.rb
app/models/user.rb

_What does your pull request propose?_ :sparkles:

Comment out ES index updates

---

config/locales/views/pages/en.yml

Fix Dr. Arindam Basu card in Home v2

---

app/controllers/stafftools/resources_controller.rb
config/initializers/inflections.rb
lib/es_indices.rb

Kept some of the changes from https://github.com/education/classroom/pull/1629 but dropped the rake task.

Centralized ElasticSearch model and index lookup

---

app/views/assignments/show.html.erb
app/views/group_assignments/show.html.erb
app/views/shared/_open_on_assistant_modal.html.erb

Reverts education/classroom#1657

Revert "Disable assignment download button"

---

app/controllers/assignments_controller.rb
app/controllers/organizations_controller.rb

Looks like I forgot one `order` term in #1667

Added missing `order` term

---

app/chewy/organization_index.rb

_Please review #1692 #1694 #1695 #1696 first_
This PR adds the `webhook_id` field to the `Organization` ES index.
Part of #1647

Add :webhook_id field to Organization index

---

config/locales/views/pages/en.yml

_What does your pull request propose?_ :sparkles:
Fixes a small typo 🙈

Fix small typo

---

config/application.rb

- Improve formatting by always adding a newline after each `raise` (as the current version of RuboCop recommends)
- Increase the timeout from 1 second to 5 seconds for all networked, GitHub API operations. As-is I could regularly reproduce timeouts by refreshing the `/_ping` endpoint ~10 times. This in turn results in flaky Pingdom checks which makes Classroom seem like it's down when it is not.
- Parse the new GitHub Status API and look specifically for the GitHub API as that's what we care about (e.g. not Issues and Pull Requests)
- Make the rate limit remaining considerable more conservative. Having 1,999 remaining requests should not make the service report a failing state.
CC @d12 and @johndbritton for review and thoughts.

config/application: improve status checks.

---

app/views/stafftools/organizations/show.html.erb

Fix template error

---

app/views/assignments/_assignment_form_options.html.erb

This clarifies that editing these particular options will not retroactively change existing assignments.

Clarify assignment form details.

---

app/controllers/application_controller.rb

Only render files for text/html requests

---

config/initializers/rack_rewrite.rb

Update the URL to the Nuts server to use HTTPS
cc @brentjo

Change Rack Rewrite URL to use HTTPS

---

app/models/concerns/github_plan.rb

The updated error message is the same as the error message suggested in #1859
Resolves #1859 
CC: @ericdrosado

Update verify_organization_has_private_repos_available with new error message

---

CODEOWNERS

Add @d12 as CODEOWNER

---

README.md

Most of us who started this week had trouble understanding the ENV variables required for setting up tests. I've updated the descriptions to more straight-forward.

Update test ENV variable descriptions in readme

---

db/migrate/20190702222417_create_lti_configurations.rb
db/schema.rb

Copied migration from https://github.com/education/classroom/pull/1947/

Migration for LTI config

---

app/controllers/application_controller/feature_flags_dependency.rb
app/controllers/assignment_invitations_controller.rb
app/controllers/group_assignment_invitations_controller.rb
app/jobs/repository_import_event_job.rb
app/models/assignment_invitation.rb
spec/controllers/assignment_invitations_controller_spec.rb
spec/controllers/group_assignment_invitations_controller_spec.rb
spec/jobs/repository_import_event_job_spec.rb
spec/models/group_assignment_invitation_spec.rb

cc #1951 
Removes import_resiliency and group_import_resiliency feature flags.

Remove import resiliency feature

---

app/views/layouts/application.html.erb
app/views/layouts/invitations.html.erb
app/views/layouts/pages.html.erb

Adds a verification meta tag to prove to Google we own the domain.

Google verification code

---

db/migrate/20190717205940_add_archived_at_to_organizations.rb
db/schema.rb

Related to #602 and #1996.
Adds the `Archived` (boolean) column to `Organization` which will eventually be used to determine if a classroom is archived.

Add archived column to Organization

---

app/views/organizations/_invite_users.html.erb
app/views/organizations/edit.html.erb
app/views/organizations/link_lms.html.erb

This was accidentally removed in my last PR when I was fixing merge conflicts.

Add back flag check 

---

app/views/pages/home.html.erb

This new example uses templates!
cc @mozzadrella

Update Classroom example link

---

app/views/assignments/_assignment_form_options.html.erb
app/views/group_assignments/_group_assignment_form_options.html.erb

A fix for https://github.com/education/classroom/issues/2277
We were setting private assignments to public. The issue was the assignment creation form.

Fixes setting private assignments to public 

---

docs/connect-to-lms.md

This PR updates our docs, to specify more clearly the LTI version we support. As well as another dependency needed: `LTI Names and Roles Provisioning 1.X`

Update docs with LTI version + Names and Roles provisioning

---

app/assets/stylesheets/help.scss

Made minor tweaks to improve presentation on smaller screens

Minor adjustments to improve mobile view

---

app/assets/javascripts/application.js
app/assets/javascripts/organization-filtering.js
app/views/organizations/_organization_filters.html.erb
package.json
yarn.lock

_What does your pull request propose?_ :sparkles:

Revert "Fix search/filter so it works on Firefox"

---

docs/create-group-assignments.md

_What does your pull request propose?_ :sparkles:

create-group-assignments.md - Small typo

---

app/controllers/pages_controller.rb
docs/creating-an-individual-assignment.md
docs/help.md
spec/controllers/pages_controller_spec.rb

The "Creating an individual assignment" doc is now linked to the help page with this PR.

Added the individual assignments doc to the help page
