education/classroom

- config/routes.rb
I usually test my apps incrementally to make sure everything works on a production environment, this fixes the return of a failure during GitHub authentication.
@johndbritton for the GitHub authentication failures, do I actually need a POST route? Or can I get away with just GET?
> Fix failure route for Heroku deployment

- app/controllers/pages_controller.rb
- test/controllers/pages_controller_test.rb
It's just been bugging me, if the user is authenticated go ahead and take them to their dashboard.
I'm leaving the static page for now because I'm assuming we'll want a splash page of some kind later down the road.
> Redirect to dashboard is the user is logged in

- .travis.yml
- script/test
To run all of the tests and the linters, you can now run `script/test`. This is also set for the Travis CI configuration in the `.travis.yml` file.
I kept forgetting to run these tests, so I thought it would be nice to have them in one script. And then if I ever update how the tests are run, it will automatically updates on Travis
> Add `test` to the script folder

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/initializers/octokit.rb
From the Octokit README
> Once configured, the middleware will store responses in cache based on ETag fingerprint and serve those back up for future 304 responses for the same resource. See the [project README](https://github.com/plataformatec/faraday-http-cache) for advanced usage.
> Caching Octokit Responses

- Gemfile
- Gemfile.lock
- config/environments/production.rb
This uses the [rack-analytics](https://github.com/railslove/rack-tracker) gem to track what's going in Classroom. Just fill in the tracking code as the `GOOGLE_ANALYTICS_TRACKING_ID` on Heroku and you're all set!
> Add Google analytics to production

- app/models/assignment.rb
- app/models/assignment_invitation.rb
- app/models/group_assignment.rb
- app/models/group_assignment_invitation.rb
- app/models/organization.rb
- db/migrate/20150806032053_soft_delete.rb
- db/schema.rb
- spec/models/assignment_invitation_spec.rb
- spec/models/assignment_spec.rb
- spec/models/group_assignment_invitation_spec.rb
- spec/models/group_assignment_spec.rb
- spec/models/organization_spec.rb
- spec/support/shared_examples/default_scope_examples.rb
This adds the `deleted_at` column to several models. This enables the user to delete something, and even if the process of it and it's resources are still being deleted the user won't be able to access it.
> Soft Delete Models

- app/models/organization.rb
- spec/models/organization_spec.rb
If two organizations have the same title but with different cases, then we get weird slugs for their urls.
> Uniqueness of the Organization title should be case insensitive

- Procfile
- app/controllers/assignment_invitations_controller.rb
- app/controllers/group_assignment_invitations_controller.rb
- app/jobs/push_starter_code_job.rb
- app/models/concerns/git_hub_repoable.rb
- app/views/invitations/_success.html.erb
- config/sidekiq.yml
Closes #94
If the user has a really large repo, the application has the potential to time out while performing the action.
This moves the process out to a background job on it's own queue `starter_code` which has a higher weight than the default queue so that the assignments will be cloned and pushed faster.
The copy and style still needs some work, but I think that's for another PR.
> Move starter code cloning and pushing to a background job

- app/jobs/push_starter_code_job.rb
- app/models/concerns/git_hub_repoable.rb
This fixes the ActiveJob::SerializationError - Unsupported argument type: GitHubRepository issue that I just created.
> ActiveJob doesn't recognize custom classes.

- app/services/auth_hash.rb
- spec/services/auth_hash_spec.rb
- spec/support/omniauth.rb
If the user is a staff member (the `site_admin` column) on GitHub then when they login they will
become staff on Classroom for GitHub.
Or if their uid is included in the NON_STAFF_GITHUB_ADMIN_IDS string
then they will also be updated to become an admin on sign in (for people like me :grin:)
> Allow GitHub Staff members to be staff on Classroom for GitHub

- app/controllers/group_assignment_invitations_controller.rb
If the user is new, they don't have a repo_access, which means they don't have groups
> Verify user has a repo_access and a group

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.coffee
- app/decorators/group_decorator.rb
- app/models/group_assignment_repo.rb
- app/views/group_assignment_invitations/accept.html.erb
- app/views/group_assignment_invitations/show.html.erb
- app/views/group_assignments/_group_assignment.html.erb
- app/views/shared/_invitation_header.html.erb
* Adds the sign out link to the invitation header
* Use the slug instead of the name for group repo creation
* Don't try to show the team name before we can
Closes #168
> Logout button missing and other things

- app/views/shared/_header.html.erb
Automatically label issues reported via the link in the app header.
https://github.com/education/classroom/labels/report
> Label new issues with `report`

- app/controllers/organizations_controller.rb
If the Organization is in the process of being reset and removed we should make sure the user can't add it to their classroom.
> Do not allow soft deleted objects to be added.

- config/initializers/octokit.rb
Fixes #234 
By default `faraday-http-cache` uses the built-in `JSON` serializer, which breaks on some edge cases. This replaces the serializer with `Marshal`.
> Use Marshal to serialize cache

- app/assets/stylesheets/layout.scss
- app/decorators/assignment_decorator.rb
- app/decorators/assignment_repo_decorator.rb
- app/decorators/group_assignment_decorator.rb
- app/decorators/group_assignment_repo_decorator.rb
- app/decorators/group_decorator.rb
- app/decorators/organization_decorator.rb
- app/decorators/user_decorator.rb
- app/models/null_git_hub_organization.rb
- app/models/null_git_hub_repository.rb
- app/models/null_git_hub_resource.rb
- app/models/null_git_hub_team.rb
- app/models/null_git_hub_user.rb
- app/models/null_github_team.rb
- app/views/assignment_repos/_assignment_repo.html.erb
- app/views/group_assignment_repos/_group_assignment_repo.html.erb
This handles `GitHub::NotFound` errors, replacing expected data with default null object data and adds disabled styles to views:
Fixes #254
> Handle missing api resources in views

- app/models/concerns/git_hub_repoable.rb
- app/models/concerns/git_hub_teamable.rb
Sometimes, a user will delete a repository by hand on github.com. When this happens, we'll now ignore the resource and continue deleting the ActiveRecord object.
Fixes #275
> Destroy even when GitHub resources are missing

- app/decorators/group_assignment_repo_decorator.rb
- app/models/null_git_hub_team.rb
Fixes #291 
`NullGitHubTeam#organization` now returns an instance of `NullGitHubOrganization.
> Disable group if the team resource is missing

- app/assets/stylesheets/layout.scss
This gives the tooltip more spacing above and is now the same as github.com
Fixes #289
> Added some spacing to navigation icons

- app/assets/stylesheets/layout.scss
- app/views/shared/_header.html.erb
Closes #289
---
Adjusted the avatar size to `18x18` and add some `margin-top` to the logo.
---
> Update header logo & avatar

- app/views/shared/_invitation_header.html.erb
Closes #314 
The Classroom for GitHub tag wasn't wrapped in an `<li>` in the `<ul>` throwing everything else off.
> Fix invitation header

- Procfile.dev
- config/sidekiq.yml
- script/sidekiq
Since we don't push code in the background anymore (#316) we don't need the queue.
> Remove starter_code background job queue

- db/migrate/20151015113741_modify_repo_access_for_collabs.rb
- db/schema.rb
These are the migrations needed for #312. These changes are to help facilitate
* Create `RepoAccesses` without `github_team_ids` we can't require them to be present
* Add the `user_id` column onto `AssignmentRepos` because `AssignmentRepos` use outside collaborators.
> Set migrations up for new collaborator changes

- Gemfile
- Gemfile.lock
- README.md
- config/initializers/airbrake.rb
- public/500.html
This adds the `airbrake` gem to report exceptions.
We only send exceptions if the `AIRBRAKE_API_KEY` environment variable is set.
> Report exceptions to Airbrake

- app/decorators/user_decorator.rb
- app/models/concerns/git_hub.rb
If a student rejects their auth token it raises a `Octokit::Unauthorized` error which we now handle.
> Gracefully handle when a student rejects their authentication token

- app/views/organizations/_invite_users.html.erb
I must have missed this one when I was [removing Zeroclipboard](https://github.com/education/classroom/pull/336)
> Fix the ability to copy classroom url for invite

- .gitignore
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
Proposal to add **simplecov** as analysis tool for tests, hence on long run it helps to increase quality and will encourage contributors to increase it as well ;) 
```
Coverage report generated for RSpec to /Users/cwirth/Workspace/classroom/coverage. 933 / 1264 LOC (73.81%) covered.
```
> adding code coverage analysis tool

- app/assets/stylesheets/.scss-lint.yml
- app/assets/stylesheets/grid-system.scss
- app/assets/stylesheets/layout.scss
- app/views/organizations/_invite_users.html.erb
- app/views/organizations/new_assignment.html.erb
- app/views/shared/_footer.html.erb
While getting back up to speed in preparation to review the upcoming staff tools changes, I noticed a few minor unrelated design things I could clean up.
First, I updated the CSS rule ordering based on our existing, preferred order. I've added an `.scss-lint.yml` which includes this ordering.
I added a subtle drop shadow to the text in the heading to help it stand out better against the patterned backgrounds. This matches what we do on https://guides.github.com and https://github.com/explore.
**Before**
**After**
I removed the indentation before this text field:
Now:
The longer group assignment description here makes this UI unbalanced. 
I'm proposing this change which I hope is still clear enough.
And finally, the current footer seems really ginormous.
I made this smaller to match our …
> Design tweaks

- app/views/stafftools/assignment_repos/show.html.erb
- app/views/stafftools/assignments/show.html.erb
- app/views/stafftools/group_assignment_repos/show.html.erb
- app/views/stafftools/group_assignments/show.html.erb
Closes #403 for stafftools I set it up so that we do all routes by id instead of by slug.
I missed some of the paths when making all of the templates.
> Make sure all organization routes on stafftools are by id only

- app/views/stafftools/users/_impersonate_user_confirmation_modal.html.erb
The modal wasn't really clear.
This is what it looks like now
> Add users GitHub login to the impersonate modal

- Gemfile.lock
- README.md
- app/assets/stylesheets/components/message-of-the-day.scss
- app/views/layouts/application.html.erb
- app/views/layouts/invitations.html.erb
- app/views/layouts/pages.html.erb
- app/views/shared/_message_of_the_day.html.erb
From @johndbritton's request by setting the `MOTD` on the server environment variable we can show a special banner at the top of all pages.
This is what it looks like right now
/cc @jasonlong because I'm sure there's a better color combination that works here, your help would be much appreciated.
> Add message of the day banner to top of the page

- config/chewy.rb
Our logs are full of Chewy debug info, this will reduce the noise.
> Set Chewy to log level info

- Gemfile.lock
I was getting segmentation faults when running `script/workers` locally. Upgrading to the latest Sidekiq `3.x` release fixed the issue.
> Bump Sidekiq to 3.5.4

- .travis.yml
Caching bundler will speed up your travis builds (mine dropped from 2:30 to about 1:00).
More info can be found [here](https://docs.travis-ci.com/user/caching).
Small note: in their docs it says that it is only available for private repos; however, in my public repos it works well.
> Cache bundler to speed up travis builds

- Gemfile
- Gemfile.lock
Upgraded to latest version of Sidekiq which drops Celluloid dependencies and includes massive speed improvements. 
Re #436.
> Re #436 - Upgrade Sidekiq to 4.5.1

- .gitignore
I'm a pretty big vim nerd and I keep my extra configs under the `config` folder for vim rails.
This ignores it for the project.
> Add vim projections to gitignore

- .gitignore
- Brewfile
- Procfile.dev
- README.md
- config/dev/nginx.conf.erb
- script/bootstrap
- script/server
- script/workers
This adds some nice things for running Classroom.
* For OSX users with Homebrew
* No longer have to run `brew install`
* Can now access `http://classroom.dev` instead of localhost
* For all users
* No longer have to open separate windows for the server and for workers.
/cc @johndbritton @mkcode
> Make the bootstrapping for Classroom easier

- README.md
The variable names in the readme was not the same as in the .env file. A grammar error is also fixed.
> environment variable names corrected

- app/views/stafftools/organizations/show.html.erb
This adds a link to the Classroom URL.
> Add classroom link to stafftools page

- app/controllers/organizations_controller.rb
Looking at my local bullet log I realized that we weren't including the `users` when we loaded the organizations on the index page.
Since we request a `github_client` from one of the users we were making more queries than we needed.
> Remove N+1 from organizations

- app/chewy/stafftools_index.rb
There are quite a few models that didn't transition from using `RepoAccess` for `AssignmentRepo` therefore when we reran the index it would fail because we weren't actually grabbing the user and therefore the `github_client` was not present.
I deployed this to branch to production, and the reindexing of Classroom was successful.
> Make sure that we are getting the AssignmentRepos user for indexing

- CONTRIBUTING.md
Now points to the right location in master branch's README.
> Fixing broken link in markdown file

- config/application.rb
We use Chewy for Elasticsearch, checking health of cluster tells us
Elasticsearch's status. i.e. ``Chewy.client.cluster.health["status"] == "green"``
Fixes #424
> Added Elasticsearch status to ``GET /_ping``

- app/views/group_assignment_invitations/accept.html.erb
While trying to reproduce #319, I found that `group_assignment_invitations/accept.html.erb` would render 2 flash messages :zap: :zap: when the repo name already exists.
The extra flash message (the lower one) is removed in the PR.
> Fix double flashes in `group_assignment_invitations/accept.html.erb`

- config/application.rb
Hey guys,
Thanks to @sahilshekhawat for #523 that added the ability to check the status of `elasticsearch`.
I've tried this locally but I found that it does not report the status correctly when my `elasticsearch` cluster is having `yellow` or `red` as its status.
This PR fixes the issue described above.
> Make `_ping` for `elasticsearch` to actually report the status.

- app/views/group_assignment_invitations/_group_assignment_team.erb
This closes #535 
When trying to find a group to join it was trying to find the group using the group assignment repo id.
/cc @johndbritton @dinever
> Use group id for finding the group in invitations

- script/setup
@tarebyte - after copying your script/setup contents I ran across a subtle bug that exists in classroom's code as well.
The `cp -n` returns non-zero status when the file already exists, which breaks out of the script because we have the '-e' parameter set.
You can verify this exists with: 
`cp -n .env-example .env; echo $?`
Cheers
> fix subtle exit status bug

- config/initializers/timeout.rb
Rack::Timeout logging in info mode is way too noisy. After this change, we will only get logs like the following when a request exceeds the timeout:
```
17:54:10 rails.1         | Rack::Timeout::RequestTimeoutException - Request ran for longer than 25000ms:
17:54:10 rails.1         |   app/controllers/pages_controller.rb:7:in `home'
17:54:10 rails.1         |   actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
17:54:10 rails.1         |   actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
17:54:10 rails.1         |   actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
17:54:10 rails.1         |   actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
17:54:10 rails.1 …
```
> set Rack::Timeout logger to warn

- app/controllers/organizations_controller.rb
This removes the ability for users with `#staff? == true` to access organization pages that they're not an admin of.
Previously, this was required for debugging. It's unnecessary now since we have an impersonation feature for staff.
I also noticed that this code is duplicated in `OrganizationAuthorization`.
I'm good with just removing this for consistency, but if you want to remove the duplication I'm for it @tarebyte.
> Remove staff access to organization pages

- Gemfile
- config/initializers/timeout.rb
Rack timeout can get rather annoying while debugging in development mode. This PR disables rack-timeout in development mode.
> Disable rack timeout in devopment

- spec/models/assignment_repo_spec.rb
There's a deprecation warning when running tests:
```
Deprecation Warnings:
Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /home/travis/build/education/classroom/spec/models/assignment_repo_spec.rb:110:in `block (6 levels) in <top (required)>'.
If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.
1 deprecation warning total
```
Looks like the `stub` method is deprecated. 
New syntax is adopted to fix this warning.
> Replace `:stub` with new RSpec syntax 

- bin/rails
- bin/rake
Discussed here: https://github.com/rubygems/rubygems/issues/1551
I was this warning
```
Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.
An Array ({"GEM_PATH"=>["/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0", "/Users/tarebyte/.gem/ruby/2.3.0"]}) was passed in from bin/rake:3:in `load'
Running via Spring preloader in process 23479
```
> Fix Array values warning

- app/assets/javascripts/navigation.coffee
- app/views/layouts/application.html.erb
Summary of changes:
- set `data-turbolinks-eval` to `false` in `javascript_include_tag 'application'` of `application.html.erb`
- remove `page:load` binding in `navigation.coffee`
Closes #607
> Prevent Javascript event callbacks from firing multiple times

- app/assets/javascripts/navigation.coffee
- app/assets/stylesheets/components/loading-indicator.scss
- app/assets/stylesheets/layout.scss
Hello guys,
Here's another minor UI tweak.
**Problem:**
When clicking a button located at the lower part of a long page, the loading indicator will not be placed at the right place.
**About this PR:**
1. Make loading indicator spans the whole viewport.
2. Disable scrolling when loading indicator is shown.
**Result**
> Fix loading indicator positioning.

- app/chewy/stafftools_index.rb
Realized [Chewy](https://github.com/toptal/chewy) had the ability to allow `includes` for an index model. This will make indexing much faster.
> Remove all n plus ones from indexes

- Gemfile
- config/initializers/pry.rb
I'd really like to have Pry in the Heroku rails console. This PR moves pry out of the development group and into the normal gemset.
> Move pry out of development group

- app.json
- config/initializers/01_redis.rb
Fixes: https://github-education.airbrake.io/projects/116727/groups/1731215870832639699
When we moved over 🔪 redis to go, I forgot to fix the internal configuration for Flipper.
This also updates the `app.json` file so people don't have to suffer using redis to go like we did.
> Fix redis for flipper

- Gemfile
- Gemfile.lock
I updated turbolinks to v5 in https://github.com/education/classroom/pull/692
I'm reverting it back down to the original version we had https://github.com/education/classroom/pull/692/files#diff-e79a60dc6b85309ae70a6ea8261eaf95L385
> Downgrade turbolinks to last known version

- app/assets/stylesheets/layout.scss
- app/views/group_assignment_invitations/_group_assignment_team.erb
- app/views/group_assignment_invitations/show.html.erb
- app/views/groupings/_group.html.erb
1. **Dropped some redundant CSS code.**
From [app/assets/stylesheets/layout.scss#L656](https://github.com/education/classroom/blob/837242724122c0a6ed047fb487ad6b6cf488f011/app/assets/stylesheets/layout.scss#L656) we can see that I've written some CSS code for this kind of style for groups:
However, we don't actually need those CSS lines since we already have [app/assets/stylesheets/components/boxed-group.scss](https://github.com/education/classroom/blob/837242724122c0a6ed047fb487ad6b6cf488f011/app/assets/stylesheets/components/boxed-group.scss), which can achieve exactly the same style.
So in this PR I removed most of the CSS lines above, and adopted `boxed-group` for the groups.
2. **Removed group member display limit in group assignment invitation page.**
Currently, if there are more …
> Team management style update

- app/controllers/assignments_controller.rb
- app/controllers/group_assignments_controller.rb
Find these logs when accessing `/classrooms/:organization_id/assignments/:id`:
```
user: cyhsutw
/classrooms/19820098-google-summer-of-code-2016/assignments/try-swift
N+1 Query detected
AssignmentRepo => [:organization]
Add to your finder: :includes => [:organization]
N+1 Query method call stack
/Users/cyhsutw/Projects/GSoC/classroom/app/models/assignment_repo.rb:48:in `github_repository'
/Users/cyhsutw/Projects/GSoC/classroom/app/models/assignment_repo.rb:36:in `disabled?'
/Users/cyhsutw/Projects/GSoC/classroom/app/views/assignment_repos/_assignment_repo.html.erb:1:in `_app_views_assignment_repos__assignment_repo_html_erb__989256760143947223_70262467422220'
/Users/cyhsutw/Projects/GSoC/classroom/app/views/assignments/show.html.erb:34:in …
```
> Fix N+1 queries when finding AssignmentRepos and GroupAssignmentRepos

- app/models/github_resource.rb
When we use a github resource and ask for an attribute, we always call from the API/cache to get the information.
This memoizes the resource that we only call it from the API/cache once per object.
```ruby
>> user.github_user.login
HTTP Cache: [GET /user/564113] valid, store
=> "tarebyte"
>> user.github_user.login
HTTP Cache: [GET /user/564113] fresh
=> "tarebyte"
```
```ruby
>> user.github_user.login
HTTP Cache: [GET /user/564113] valid, store
=> "tarebyte"
>> user.github_user.login
=> "tarebyte"
```
> Memoize resource after first use

- app/controllers/assignments_controller.rb
- app/controllers/group_assignments_controller.rb
Updating the `Give students Admin permissions on their repository` of assignments / group assignments does not work since `students_are_repo_admins` is not permitted in the `update_group_assignment_params` / `update_group_assignment_params`.
```
09:52:33 rails.1 | Started PATCH "/classrooms/19820098-classroom/group-assignments/homework" for 127.0.0.1 at 2016-09-12 09:52:33 +0800
09:52:33 rails.1 | Unpermitted parameter: students_are_repo_admins
```
> Add :students_are_repo_admins to permitted params

- app/assets/javascripts/application.coffee
- app/assets/stylesheets/components/progress-bar.scss
- app/views/assignments/_assignment.html.erb
- app/views/assignments/_delete_assignment_modal.html.erb
- app/views/assignments/edit.html.erb
- app/views/assignments/show.html.erb
- app/views/group_assignment_invitations/accept.html.erb
- app/views/group_assignments/_delete_group_assignment_modal.html.erb
- app/views/group_assignments/_group_assignment.html.erb
- app/views/group_assignments/edit.html.erb
- app/views/group_assignments/show.html.erb
- app/views/groupings/edit.html.erb
- app/views/organizations/_organization_select.html.erb
- app/views/organizations/_reset_and_remove_organization_modal.html.erb
- app/views/shared/_assignment_student_identifier_type_options.html.erb
- app/views/shared/_identifier_form.html.erb
- app/views/stafftools/users/_impersonate_user_confirmation_modal.html.erb
- app/views/student_identifier_types/_student_identifier_type.html.erb
- app/views/student_identifier_types/edit.html.erb
- app/views/student_identifier_types/new.html.erb
Closes https://github.com/education/classroom/issues/750
I don't really want to update all of our javascript for Turbolinks 5 right now. In the mean time this enables the progress bar for [Turbolinks 2.5.3](https://github.com/turbolinks/turbolinks-classic/tree/v2.5.3#progress-bar) and fixes the styling.
I've also remove all of the places I think the `js-navigation` class was a problem.
@dinever @cyhsutw if you see a place I removed that it was not an issue, please let me know.
> Enable Turbolinks progress bar

- .travis.yml
- app/controllers/groups_controller.rb
- app/controllers/hooks_controller.rb
- app/jobs/ping_event_job.rb
- app/models/github_repository.rb
- config/routes.rb
- config/sidekiq.yml
- lib/github/web_hook.rb
- spec/controllers/hooks_controller_spec.rb
- spec/controllers/stafftools/users_controller_spec.rb
Largely off based on the work of @cyhsutw in https://github.com/education/classroom/pull/694.
This allows Classroom to start receiving [GitHub webhook events](https://developer.github.com/webhooks/#events).
Each event will have it's own background job, so for example  the [`ping`](https://developer.github.com/webhooks/#ping-event) event has the job `PingEventJob`. Which as of right now does nothing.
I'm extracting this work for a few reasons:
- The original PR is rather large, and I'd like to break it down for easier reviewing
- I wanted to make the route more flexible for all kind of events
- I wanted to move responsibility to the background job instead of at the controller level.
/cc @cyhsutw
> Receive webhooks

- app/views/stafftools/assignment_repos/show.html.erb
- app/views/stafftools/group_assignment_repos/show.html.erb
This adds link us to the source code on GitHub for each `AssignmentRepo` and `GroupAssignmentRepo`.
> Add source code links to stafftools

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/jobs/last_active_job.rb
- spec/jobs/last_active_job_spec.rb
- spec/rails_helper.rb
During tests the records are deleted so quickly that the job can't find the record and deletes it.
~~This passes the id of the record and then does a query for it.~~
I'm just gonna do a second lookup using the old record.
> Fix last active in tests

- Gemfile
Fix a slight warning while installing gems:
```bash
$ bundle        
Your Gemfile lists the gem timecop (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
....
```
/cc @tarebyte
> [Development] Remove duplicate gem entry `timecop`

- app/assets/javascripts/application.js
- vendor/assets/bower.json
- vendor/assets/bower_components/fetch/.bower.json
- vendor/assets/bower_components/fetch/LICENSE
- vendor/assets/bower_components/fetch/bower.json
- vendor/assets/bower_components/fetch/fetch.js
Closes #794 
The cause of #794 is we're missing `Request` in Safari. The [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/Request#Browser_compatibility) of [`Request` on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Request) shows that Safari does not have a built-in implementation of `Request` yet.
To address this, we should also add another polyfill to support `Request`. The polyfill used in this PR is [`github/fetch`](https://github.com/github/fetch).
Sorry for not identifying the problem in #777 😥
Tested on macOS 10.11.6 with:
- Google Chrome 54.0.2840.98 (64-bit)
- Mozilla Firefox 50.0
- Safari 10.0.1
> Polyfill ”fetch“ to support async resource loading using “include-fragement” element

- db/migrate/20161130020119_change_webhook_id_column_to_integer.rb
- db/schema.rb
From https://github.com/education/classroom/pull/797
This casts the `Organizations` column `webhook_id` to be an `int` instead of a `string`
> Cast webhook_id to be int instead of string

- app/models/assignment_repo/creator.rb
Closes #808 because I'm an idiot.
I was making public assignments during my tests, but my test org has a plan so I never ran into this issue.
/cc @tamastompa @immanuelfodor
> Allow public assignments for orgs that don't have a plan.

- config/initializers/scopes.rb
- spec/lib/github_classroom/scopes_spec.rb
Closes #817 
There was a change in the [Preview Repository Invitations API](https://developer.github.com/v3/repos/invitations/) where we now need to include the `repo` scope in order to accept the invitation on the students behalf.
This updates students scopes on Classroom so that everything should work again.
> Add repo scope for students

- app/models/assignment_repo/creator.rb
- config/initializers/scopes.rb
- spec/lib/github_classroom/scopes_spec.rb
Closes #819 
Because of the scope changes in #818 I borked some students ability to accept assignments. I'm still on vacation so for the time being I'm going to revert the use of the Beta API so that we can use the old scopes.
> Revert use of Repository Invitations

- README.md
The current link points to a 404 page, the new link points to an updated guide for setting up Elasticsearch.
> Update elastic link

- config/environments/development.rb
- config/initializers/peek.rb
We should use memcached in development as well as production. This also only shows the dalli peek view if we are caching.
> Use memcache in development and only show in peek bar when used

- README.md
I was getting ready to start over on a piece of work I was doing and going through the documentation again. I received the following failure when running the setup script:
```bash
vagrant@homestead:~/Code/classroom$ script/setup
==> Installing gem dependencies…
rbenv: version `2.4.0' is not installed (set by /home/vagrant/Code/classroom/.ruby-version)
```
After installing 2.4.0, reinstalling bundler and rehashing, the setup script started executing.
> Require Ruby 2.4.0 in "Getting Started" documentation

- .github/stable.yml
@tarebyte has installed Probot: Stale to Classroom, this PR adds the necessary config file. 
I've left most of the config defaults alone, but added feature-request to the exempt list. I don't think feature requests really go stale, it might be a while until we can get around to a specific one but I think we can assume it's still a valid feature unless we close ourselves.
> Add Probot stale config file

- app/assets/stylesheets/layout.scss
Normally, we don't use `<p>` tags in flash messages. In assignment/new and group-assignment/new though, we use them to separate many different errors. This fixes a visual bug caused by `<p>` tags having a margin-top.
Before: 
After:
> Fix styling issue with flash errors

- app/controllers/organizations_controller.rb
- app/views/organizations/_disabled_organization_select.html.erb
Closes #845 
Display a more informative message with the owners login when we cannot use an org for a classroom because it is already used by another Classroom
@johndbritton @tarebyte
> More informative error message when trying to create a classroom with an Org that's in use

- app/controllers/application_controller.rb
- public/404.html
- public/invalid_link_error.html
- spec/controllers/groupings_controller_spec.rb
- spec/controllers/groups_controller_spec.rb
- spec/controllers/organizations_controller_spec.rb
- spec/controllers/stafftools/assignment_invitations_controller_spec.rb
- spec/controllers/stafftools/assignment_repos_controller_spec.rb
- spec/controllers/stafftools/assignments_controller_spec.rb
- spec/controllers/stafftools/group_assignment_invitations_controller_spec.rb
- spec/controllers/stafftools/group_assignment_repos_controller_spec.rb
- spec/controllers/stafftools/group_assignments_controller_spec.rb
- spec/controllers/stafftools/groupings_controller_spec.rb
- spec/controllers/stafftools/groups_controller_spec.rb
- spec/controllers/stafftools/organizations_controller_spec.rb
- spec/controllers/stafftools/repo_accesses_controller_spec.rb
- spec/controllers/stafftools/resources_controller_spec.rb
- spec/controllers/stafftools/users_controller_spec.rb
- spec/controllers/student_identifier_types_controller_spec.rb
Modify existing `404.html` to handle Routing Exception and add `invalid_link_error.html` to handle RecordNotFound exception.
Closes #432
Screenshots: 
- `invalid_link_error.html`
- `404.html`
> Add Error pages for RoutingError and RecordNotFound exceptions

- config/dev/nginx.conf.erb
This moves the nginx.conf.erb file back to port 5000
/cc @wilfriedE
> Fix Nginx dev config

- app/models/assignment_repo.rb
- spec/models/assignment_repo_spec.rb
Rails 5 enforces validations on `belongs_to` that the thing exists, but none of our new `AssignmentRepo`s have a `repo_access` (legacy reasons).
This was causing exceptions every time we tried to update an `AssignmentRepo`.
@tarebyte
> Make repo accesses optional for assignment repos

- app/models/assignment/editor.rb
- app/views/assignments/_assignment_form_options.html.erb
- app/views/group_assignments/_group_assignment_form_options.html.erb
Since we didn't add errors on the `@assignment` object, the view had no idea something had gone wrong with the deadline. Also, we didn't have the FormView tooltip logic in the view.
@tarebyte
> Fix errors on deadlines

- app/models/assignment_repo.rb
- app/models/group_assignment_repo.rb
While doing some profiling last week, I noticed that our calls to `disabled?` are causing a TON of API requests on `group_assignment/show` and `assignment/show`, coming from the `group_assignment_repo/show` and `assignment_repo/show` partials.
On an assignment repo, we make 3 `disabled?` calls, which equals 6 API requests.
On a group assignment repo, we make between 3 and 8 `disabled?` calls depending on the number of team members, which equals 6 - 16 API requests.
The value of `disabled?` shouldn't change during the time we're rendering these partials, so memoizing won't have any visible impact. It will, though, bring both of these partials down to only 2 API requests.
@tarebyte @johndbritton
> Memoize disabled? to save a ton of API requests

- db/migrate/20170629200720_remove_identifier_tables.rb
- db/schema.rb
A migration to remove the rows and tables in the schema related to the old implementation of identifiers.
The diff looks gnarly right now because this is based on #975, once that's merged, this'll look cleaner. The changes are in the latest commit.
> Migrations to remove identifier stuff

- db/migrate/20170629203747_add_new_identifier_tables.rb
- db/schema.rb
Works towards #986 
As discussed here: https://github.com/education/classroom/issues/448#issuecomment-311786419
These are the new tables for rosters. Since an organization belongs to a roster, the organization now has a `roster_id` column
> Migration to add tables for new roster models, + roster_id on org

- app/models/user.rb
Forgot this association in my last PR. A RosterEntry belongs_to a User, so a User should has_many RosterEntry.
> Add missing association on user

- app/view_models/shared_assignment_repo_view.rb
Right now, if `default_branch` errors, it bubbles all the way to ActionView and then we crash.
This PR adds handling in the view model. Also, because of the way the detail partials work, by returning `''` as the `url` in the error case, the partial is rendered as a `span` instead of a `a`.
@tarebyte
> Show failure text if we error when trying to get branch

- app/assets/stylesheets/layout.scss
> Fix styling on error partial

- app/models/organization.rb
- spec/models/organization_spec.rb
This is only being triggered by `PingJob`s right now, but it's throwing exceptions. Orgs without a Roster should not be invalid.
> Rosters should optionally belong to an organization

- CODEOWNERS
@wilfriedE isn't getting set as a codeowner. I guess codeowners is case sensitive.
> Capitalize the letter in wilfriede's handle for CODEOWNERS

- app/models/assignment_invitation.rb
- app/models/group_assignment_invitation.rb
- spec/models/assignment_invitation_spec.rb
- spec/models/group_assignment_invitation_spec.rb
We should not be running uniqueness checks for invitations with nil short_keys (e.g. all existing invitations).
Also wrote regression specs for assignment and group assignment invitation.
> Don't run uniqueness validation for invitations with nil short keys

- app/models/assignment/editor.rb
Introduced in #976 :/
Right now, we can't clear deadlines because we try to `strptime` the empty string.
Side note: We really need a spec for the editor, it's getting really complex. See #1016
> Fix deadline regression

- app/assets/javascripts/datetimepicker.js
Thanks @mozzadrella for doing user testing and finding this UX issue ✨ 
Currently when you don't have a deadline, the datepicker time defaults to the current hour and 0 minutes, which means the default deadline is always in the past and is invalid.
In most cases, the teacher will be selecting a deadline from the datepicker, but if someone just accepts the default deadline (maybe to see how the deadlines feature works), we shouldn't error.
We now default to the NEXT hour.
Also: This is the last fix before everything has been addressed. After that, we should be 🍏 to full ship.
> Default deadline datepicker time to next hour

- app/controllers/short_url_controller.rb
- spec/controllers/short_url_controller_spec.rb
When a user hits the short_url controller, the before action in `application_controller` asks for full teacher scopes. 
We should skip and authenticate after we redirect.
@tarebyte @johndbritton
> Fix permissions error

- Gemfile
- Gemfile.lock
- config/boot.rb
[Bootsnap](https://github.com/Shopify/bootsnap) by Shopify was just added to [Rails core](https://github.com/rails/rails/pull/29313), so I figured what the heck why not ¯\\_(ツ)_/¯
> Add bootsnap gem

- spec/models/assignment/editor_spec.rb
Closes #1041 
We've had 2 regressions in the last month on the editor. This PR adds a testing suite to hopefully help prevent these in the future.
> Create assignment/editor testing suite

- app/assets/stylesheets/layout.scss
The current delete button is sort of bugging me: Way too much red.
Idea 1:
Idea 2 (taken from the GitHub modal styles)
Preferences? I'm leaning towards 2, especially since it's what we use right now in our modals.
/cc @mozzadrella
> Different hover color for delete roster entry button

- app/controllers/group_assignments_controller.rb
- app/controllers/roster_entries_controller.rb
- app/views/group_assignments/show.html.erb
- config/routes.rb
Closes #990 
This is the new view for group assignments with a roster. Only orgs with a roster will see the new view.
The first tab is identical to the old view. The second tab shows student that have not yet accepted the assignment. This includes students that haven't joined the classroom yet, or have just not joined a team yet.
~~TODO: Specs~~
Nevermind, there's no logic added in this PR.
> Change group assignment show view to support rosters

- config/initializers/statsd.rb
Start logging response times to statsd
We filter out peek requests because they're almost instant and not interesting at all.
> Log response times to statsd

- app/views/group_assignment_invitations/show.html.erb
Closes #974 
Fixes some outdated classes on a textbox.
> Fix styling on create team textbox

- Gemfile
- Gemfile.lock
- config/application.rb
This adds the Failbot gem so that I can get some better reporting on Classroom in our internal tooling.
This shouldn't be an issue for non GitHub based instances.
> Add and configure Failbot

- app/views/shared/_shared_join_roster.html.erb
Based on this: https://github.com/education/classroom/issues/1239
The roster shown to a student when they first log in to choose their IDs is now **sorted** ✨ !
> Sort roster entries based on identifier

- Gemfile.lock
I got a notification for https://github.com/education/classroom/network/dependencies#35074859
This updates bumps Nokogiri to 1.8.2
> Update Nokogiri to mitigate CVE-2017-9050

- db/migrate/20180131020132_drop_unique_github_id_index_on_organizations.rb
- db/schema.rb
Working towards https://github.com/education/classroom/issues/595
This removes the unique index on `github_id` at the database level for the `organizations` table.
Until the feature is complete we need to keep the unique index at the model level, but this is a good first start.
> Drop unique index on github_id for Organizations

- app/models/roster_entry.rb
- spec/models/roster_entry_spec.rb
Apparently `IN ()` is invalid syntax in postgres and none of my specs caught that -_-
Instead of `()`, we use `(NULL)` as the empty collection, which works in both cases.
I also added a regression test.
@tarebyte
> Fix for pagination bug

- app/controllers/orgs/rosters_controller.rb
- spec/controllers/orgs/rosters_controller_spec.rb
Fix for #1291 
I forgot to remove pagination for the download button on my last PR 🙈 
The download button returned only the first 20 students not all of them as it should have.
I removed pagination so it returns now all of the students from the roster.
TODO:
> Remove pagination for download

- app/views/shared/_header.html.erb
- app/views/shared/_invitation_header.html.erb
- config/locales/views/shared/en.yml
Based on #1304 
For now we just have an icon that redirects to a [filtered](https://github.com/education/classroom/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc) page on GitHub with all the last pull requests that were merged 👍
> Classroom's changelog #1

- app/models/roster_entry.rb
This PR address https://github.com/education/classroom/issues/1310
The downloaded roster now include a student's GitHub ID (if the account is linked)
Let me know if there needs to be changes!
> Including GitHub IDs in downloaded rosters

- app/controllers/assignments_controller.rb
Me and @Kadaaran spent an hour or so yesterday picking apart the app trying to find inefficiencies causing long load times for large classrooms. The main issue ended up being an [Octokit bug](https://github.com/octokit/octokit.rb/issues/912), but we did come across another performance bug that affects large classrooms.
`.roster_entries.map(&:user)` loads the user records for each roster entry, but the way it's written, we make 1 SQL query per roster entry. Me and @Kadaaran tested this line of code against a classroom with 450 roster entries and it took `2.0s` to run.
The refactored logic makes a single batched query.
cc @tarebyte
> Fix N+1 in calculating unlinked users

- app/controllers/group_assignments_controller.rb
Fix to #1303 
Found out that the bug is linked to #1228 @d12 🙏 
This issue occurs in a particular situation: in the group_assignment page for organizations without roster.
This line was sending to the partial another page parameter than the regular one we should have.
https://github.com/education/classroom/blob/3b01242b9c5f769a1fa12234c83723713851f8fd/app/controllers/group_assignments_controller.rb#L32
https://github.com/education/classroom/blob/3b01242b9c5f769a1fa12234c83723713851f8fd/app/views/group_assignments/show.html.erb#L99
**TODO**:  Write test (which are not overkill) for pagination
> Fix pagination for non rosters orgs

- README.md
Hey 👋 
Saw that the `help-wanted` link was using referring to the old [`help-wanted`](https://github.com/education/classroom/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted) label (without the emoji). 
The new [`help-wanted`](https://github.com/education/classroom/issues?q=is%3Aissue+is%3Aopen+label%3A%22%3Ahand%3A+help-wanted%22) link reflects the label that is being used (with the emoji).
> Change `help-wanted` link to reflect emoji label

- config/cable.yml
Looks like there was a lot of `Redis::CannotConnectError`. This is because ActionCable wasn't configured properly. Good news is that this didn't affect any teachers/students flows but caused a firehose of `Redis::CannotConnectError` and `5xx` on `/cable`.
Originally part of #1385 but being pulled out.
> Configure Redis adapter for ActionCable

- app/jobs/assignment_repo/create_github_repository_job.rb
- spec/jobs/assignment_repo/create_github_repository_job_spec.rb
The concurrency problem with `CreateGitHubRepositoryJob` is that you could kick off two jobs that could create two repos. We want `CreateGitHubRepositoryJob` to only create one repo always.
We do this by short circuiting the job and returning early if the invitation status is:
* `unaccepted` (if the invitation wasn't accepted)
* `creating_repo` (if a job is already creating a repo)
* `importing_starter_code`(if starter code is being imported already)
* `completed` (if a repo already exists)
Closes #1392
> Fix concurrency issue with CreateGitHubRepositoryJob

- app/assets/javascripts/setupv2.js
The poll interval was previously 3 seconds and there is a large discrepancy between when a import actually finishes vs when classroom thinks it finishes.
I will do some investigating to why there is a large discrepancy but this should make the problem slightly worse for now.
> Reduce poll interval to 1s instead of 3s

- app/jobs/assignment_repo/create_github_repository_job.rb
- spec/jobs/assignment_repo/create_github_repository_job_spec.rb
This PR removes automatic retries from `CreateGitHubRepositoryJob`
Retries are funneling up to our error reporting software even when they aren't necessarily errors.
We have a manual retry button on the setupv2 page so it would reduce complexity and do away with automatic retries in place of manual retries.
---
Closes #1416
> Remove automatic retries in repo creation process

- db/migrate/20180723230724_remove_status_from_assignment_invitation.rb
- db/schema.rb
In #1425 the `status` attribute on `AssignmentInvitation` was moved to its own child model `InviteStatus`. Because of this there is no need for a `status` column on `assignment_invitations`. 
This PR proposes a migration to remove the `status` column.
This is failing until #1425 merges.
> Assignmentinvitation drop status column

- app/controllers/assignment_invitations_controller.rb
Looks like there was case where it was using the `status` on `AssignmentInvitation` which must have been a bad patch from before #1425
> Use new current_invitation_status

- app/models/github_repository/import_dependency.rb
Possibly why there is a discrepancy between the time of import completion and when the UI presents completion is that the `client.source_import_progress` is hitting the cache and thus is not necessarily up to date.
This PR proposes that we include the header in our import progress request: 
```ruby
{ "Cache-Control" => "no-cache, no-store" }
```
> Don't hit the cache on polling progress

- app/assets/javascripts/setupv2.js
- app/jobs/assignment_repo/create_github_repository_job.rb
- app/jobs/assignment_repo/porter_status_job.rb
- app/views/assignment_invitations/setupv2.html.erb
- spec/jobs/assignment_repo/create_github_repository_job_spec.rb
- spec/jobs/assignment_repo/porter_status_job_spec.rb
This PR adds a JS function to take `ActionCable` messages and render their `error` and `text` fields.
This allows us to funnel up errors to the user (where we previously couldn't).
closes #1443
> Render ActionCable errors

- app/assets/javascripts/setupv2.js
- app/assets/stylesheets/components/progress-bar.scss
- app/jobs/assignment_repo/porter_status_job.rb
- app/views/assignment_invitations/setupv2.html.erb
- spec/jobs/assignment_repo/porter_status_job_spec.rb
This PR introduces some UI improvements to the create/import flow.
* Progress bars instead of spinners
* PorterStatusJob broadcasts `status_text` and `percentage`
* Status text in the sub-line of each step
--- 
Closes https://github.com/education/classroom/issues/1420
> Better progress indication

- lib/octopoller.rb
- spec/lib/octopoller_spec.rb
@d12 [said](https://github.com/education/classroom/pull/1400#discussion_r203068588) that it would be nice to have a a function that attempts a action given a # of attempts. This PR proposes a new Octopoller function `try`.
It's API is very similar to the `poll` API:
```ruby
Octopoller.try(wait: 1.second, attempts: 2) do
result = put_in_usb_stick()
:retry if result.success?
end
```
There is also an exponential backoff retry:
```ruby
start = Time.now
Octopoller.try(wait: :exponentially) do
puts (Time.now - start).seconds
end
```
What are your thoughts and ideas about the API? Can it be improved? Is this what you hoped it would look like?
> Octopoller.try 

- app/jobs/assignment_repo/create_github_repository_job.rb
- spec/jobs/assignment_repo/create_github_repository_job_spec.rb
This ensures the correct argument is passed. Previously it was passing a bool value. Now it is passing the `AssignmentRepo` object.
> Fix arg passed

- app/jobs/assignment_repo/porter_status_job.rb
- spec/jobs/assignment_repo/porter_status_job_spec.rb
This PR proposes:
* we reduce porter status polling from once a second to once every ten seconds
* we add a data dog event for each time we poll the source imports API (`v2_exercise_repo.import.poll`)
This resolves the incident that occurred today.
Resolves #1536 #1537
> Reduced porter status polling + added data dog event

- app/controllers/orgs/rosters_controller.rb
- spec/controllers/orgs/rosters_controller_spec.rb
Source of the problem was the ES connection.
Temporary fix, as this isn't as efficient as the ES query.
Fixes #1557. 
```ruby
result = User.where(id: [1, 2, 3])
User Load (17.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (1, 2, 3, 4, 5, 6)
=> [#<User:0x00007f90b40491c8
id: 2,
uid: 41388586,
token: "f53e9d03d4970755f76d7895db58866ec049f391",
created_at: Fri, 03 Aug 2018 21:03:11 UTC +00:00,
updated_at: Fri, 03 Aug 2018 21:03:11 UTC +00:00,
site_admin: false,
last_active_at: Mon, 10 Sep 2018 21:43:41 UTC +00:00>,
#<User:0x00007f90b04587b8
id: 3,
uid: 41803513,
token: "cc0842800795c0fbd5639c8ef00cf4affb6914d9",
created_at: Fri, 03 Aug 2018 21:21:00 UTC +00:00,
updated_at: Fri, 03 Aug 2018 21:21:00 UTC +00:00,
site_admin: false,
last_active_at: Fri, 07 Sep 2018 14:19:44 UTC …
```
> Fix roster es query

- app.json
- config/chewy.yml
This PR changes all instance of bonsai to elasticsearch ("elasticsearch"  has the prefix "found" in heroku land).
> Switch from Bonsai to Elasticsearch

- db/migrate/20180918215254_global_relay_fields_for_assignments_orgs_and_users.rb
- db/schema.rb
cc https://github.com/education/classroom/issues/1518
The initial migrations for GraphQL work in Classroom to begin.
`assignment_repos` had a field already from some spike work I did a year ago, but I renamed it to be more correct. The things we store in the database are GitHub global relay IDs, not local global relay IDs, as those can be calculated at runtime.
I also removed the index since we'll never be `SELECT`ing or ordering by the global relay ID.
> Migrations for GraphQL work to begin

- docker-compose.yml
This PR proposes we bump our docker image of ES to 6.3.2 to reflect the version that our service provider is providing us. This will help us resolve breaking ES changes locally.
Docs: https://www.elastic.co/guide/en/elasticsearch/reference/6.3/docker.html
> Bump ES to 6.3.2

- app/jobs/group_assignment_repo/create_github_repository_job.rb
- spec/jobs/group_assignment_repo/create_github_repository_job_spec.rb
Remove TODO comments about a `GroupAssignmentRepo` `PorterStatusJob`.
We have since taken the approach to use webhooks instead of polling the GitHub API (#1498)
> Remove TODOs

- app/views/pages/_download_assistant_button.html.erb
There was a typo in one of the download links for downloading Assistant 🍎
> Fix linux download link for Assistant

- app/assets/javascripts/setup.js
- app/channels/repository_creation_status_channel.rb
- app/controllers/assignment_invitations_controller.rb
- app/jobs/assignment_repo/create_github_repository_job.rb
- app/jobs/repository_import_event_job.rb
- app/views/assignment_invitations/setup.html.erb
- app/views/group_assignment_invitations/setup.html.erb
- spec/channels/repository_creation_status_channel_spec.rb
- spec/jobs/assignment_repo/create_github_repository_job_spec.rb
- spec/jobs/repository_import_event_job_spec.rb
Currently if you try to accept two individual assignments at the same time, their ActionCable messages get broadcasted to each others setup process. This is not ideal.
This PR proposes we add another level of identification to the `RepositoryCreationStatusChannel` by giving it an `assignment_id` argument. 
By giving it an `assignment_id` argument, we will prevent messages being cross broadcasted to other repository setup processes.
> Add 'assignment_id' argument to RepositoryCreationStatusChannel

- app/chewy/assignment_index.rb
- app/chewy/assignment_invitation_index.rb
- app/chewy/assignment_repo_index.rb
- app/chewy/group_assignment_index.rb
- app/chewy/group_assignment_invitation_index.rb
- app/chewy/group_assignment_repo_index.rb
- app/chewy/group_index.rb
- app/chewy/grouping_index.rb
- app/chewy/organization_index.rb
- app/chewy/repo_access_index.rb
This avoids hitting exceptions during bulk index syncs / imports by ensuring we never call a method on `nil`.
> Don't call methods on nil when indexing

- config/application.rb
If our app level rate limit is close to exhausted, trigger an alert.
This should almost never happen, so I feel ok with it being in the app health status.
> Alert when rate limit gets low

- app/jobs/assignment_repo/create_github_repository_job.rb
- app/models/assignment_repo.rb
- spec/models/assignment_repo_spec.rb
This PR proposes a fix for #1646 
In https://github.com/education/classroom/issues/1462 I checked to see if each duplicate GitHub repo had an associated `AssignmentRepo` and I found that there were two assignment repos for the same `<User, Assignment>` key.
```ruby
PRODUCTION [2] pry(main)> a1 = AssignmentRepo.find_by(github_repo_id: 142300727)
D, [2018-10-15T19:22:26.217594 #4] DEBUG -- :   AssignmentRepo Load (1.2ms)  SELECT  "assignment_repos".* FROM "assignment_repos" WHERE "assignment_repos"."github_repo_id" = $1 LIMIT $2  [["github_repo_id", 142300727], ["LIMIT", 1]]
=> #<AssignmentRepo:0x0000000008381eb0
id: 741547,
github_repo_id: 142300727,
repo_access_id: nil,
created_at: Wed, 25 Jul 2018 13:02:41 UTC +00:00,
updated_at: Wed, 25 Jul 2018 13:02:41 UTC +00:00,
assignment_id: …
```
> Prevent duplicate AssignmentRepos

- .travis.yml
- app/controllers/orgs/rosters_controller.rb
- config/application.rb
- lib/tasks/locked_invite_status_migration.rake
This PR moves our linting process to TravisCI instead of Hound. Hound crashes when we upload a specific vendored Gem. Until that's fixed, let's move to TravisCI for now.
> Move linting to travis

- app/controllers/assignments_controller.rb
- app/controllers/group_assignments_controller.rb
- app/controllers/orgs/rosters_controller.rb
This PR proposes a fix for #1661 and #1659 
There appears to have been weird behavior when querying without `order` on Assignments#show
https://github.com/education/classroom/blob/master/app/controllers/assignments_controller.rb#L33-L39
1. I discovered that our paginated assignment repo query was producing duplicates and missing records: https://github.com/education/classroom/issues/1659#issuecomment-431140486
1. I uncovered that there wasn't anything wrong with our pagination gem since I was able to reproduce the bug using `limit` and `offset`: https://github.com/education/classroom/issues/1659#issuecomment-431140486
1. Then I finally discovered that adding `order(:id)` would prevent duplicates and missing records in pagination: …
> Order paginated requests

- app/controllers/api/assignment_repos_controller.rb
- app/controllers/api/group_assignment_repos_controller.rb
Related to #1667 and #1670 
Fixes https://github.com/education/classroom-assistant/issues/113
Looks like this issue has been affecting Classroom Assistant as well since the API has been returning duplicated assignments/missing assignments because there is no `order` in the query
> Add order to API Calls

- db/migrate/20181101185901_create_organization_webhooks.rb
- db/migrate/20181101185917_add_organization_webhook_ref_to_organizations.rb
- db/schema.rb
This PR proposes we add a new model named `OrganizationWebhook` which has 2 purposes:
1. keep a record of when the last webhook was received using the `last_webhook_recieved` column 
1. persist and manage an organization's webhook via its `github_webhook_id` column
It might be too write heavy on the Organization model if we commit to writing to it every time we get a webhook event.
Part of #1647
Models for this coming in a follow up PR
> Organization webhook migration

- app/models/organization/creator.rb
- app/models/organization_webhook.rb
- lib/tasks/organization_webhook_backfill.rake
- spec/models/organization_webhook_spec.rb
- The model migration was introduced in #1692 
- The model was introduced in #1694 
☝️ Review these first
This PR proposes a task to backfill `Organizations` to belong to an `OrganizationWebhook`.
The task can be found in `lib/tasks/organization_webhook_backfill.rake`
Part of #1647
> Organization webhook model backfill

- app/models/organization_webhook.rb
- spec/models/organization_webhook_spec.rb
This PR proposes we add `has_many :users, through: :organizations` to `OrganizationWebhook`.
Part of #1647
> Adds has_many Users through Organizations to OrganizationWebhook

- app/models/organization_webhook.rb
- spec/models/organization_webhook_spec.rb
This PR proposes methods for `OrganizationWebhook` to find User tokens with the `admin:org_hook` scope. These tokens are required to create webhooks for organizations.
In a follow up PR I will make the methods for creating the webhooks using these tokens.
Part of #1647 
> - [ ] move the logic for creating a webhook from the `Organization::Creator` to `GitHubOrganizationWebhook`
> Finds a User's token that has the `admin:org_hook` scope

- app/controllers/group_assignment_invitations_controller.rb
- app/models/group_assignment_invitation.rb
- spec/controllers/group_assignment_invitations_controller_spec.rb
- spec/models/group_assignment_invitation_spec.rb
This PR proposes the following changes:
* removed the before_action `check_group_not_previous_acceptee` from `group_assignment_invitations_controller.rb`. This before_action was previously solving an edge case before the `group_import_resiliency` changes went into place, but is no longer needed since we now have `route_based_on_status`.
* in `#create_repo` we now check if a pre existing assignment repo is present. If that assignment repo is ready, succeed otherwise retry the repo creation process.
A lot of dead code still exists behind the `group_import_resiliency` and we must make an issue to clean that up!
Fixes #1704
> Fix too many redirects bug

- app/models/organization.rb
- spec/models/organization_spec.rb
This Pr proposes we add the method `#in_good_health?`, which performs a trivial check to see if a an organization has a hook id. This method will be used to prevent users from trying to use classrooms that don't have webhooks (so will invoked a lot).
Part of #1647 
> - [ ] define a method to check if an `Organization` meets all minimum requirements
>   - if webhooks are present and enabled
> Added method #in_good_health? to organization model

- app/models/organization.rb
- spec/models/organization_spec.rb
Reverts education/classroom#1724 because this functionality is no longer needed (as discussed in #1647)
> Revert "Added method #in_good_health? to organization model"

- app/controllers/organizations_controller.rb
- app/models/github_organization.rb
- app/models/organization.rb
- app/views/organizations/_organization_banner.html.erb
- app/views/organizations/_organization_invitation_banner.html.erb
Updated the flash banner message when an org is deleted and moved the background generation for each Classroom page onto the `Organization` model from `GitHub_Organization` (also allows us for more UI upgrades coming in the future 😄)
> Multiple Classrooms per Org UI Tweaks

- app/views/organizations/new.html.erb
Removed the pre-release badge for feedback on multiple classrooms per org since we've shipped to the public!
> Remove Pre-release badge for Multiple classrooms

- db/schema.rb
I brought in the `ticker_stats` table into `schema.rb` inadvertently when we were working on the Classroom Assistant launch. At the time we were planning on adding a repository ticker visualization to the Classroom homepage which has since been scrapped. The actual migration file was never committed so rails automatically deletes this snippet every time the app is run locally right now.
> Drop Ticker Stat Schema

- app/views/organizations/_organization_card_layout.html.erb
Sort order on Latest Assignments in the new dashboard assignment cards is flipped. This PR reverses the assignments selected
> Fix Assignment Sorting on Dashboard

- app/views/shared/_invitation_header.html.erb
Fixes #1830.
Looks like we have a separate header partial for the invitations view that is very similar to the main header partial. I simply copied the styling from the [main header](https://github.com/education/classroom/blob/master/app/views/shared/_header.html.erb) to this one.
> Fix header styling on assignment invitations

- app/views/shared/_header.html.erb
- app/views/shared/_invitation_header.html.erb
* Previously the link would take you page where you draft a new bug issue: https://github.com/education/classroom/issues/new?template=bug_report.md
* Now the link would take you to the page where you can see the issues board: https://github.com/education/classroom/issues
By bringing future bug reporters to the issues board first, they will be more likely to see if the issue they are experiencing already exists. This will hopefully reduce the number of duplicate issues.
> Link to issues page

- app/controllers/assignments_controller.rb
I ran into the bug we had seen earlier in #1657 again where the Download Repositories button was getting disabled for some assignments even when the assignment had repos to download. 
The problem was that the variable `@assignment_repos` was only getting defined by the controller when the assignment had a roster. When we checked if there were any assignment repos (`@assignment_repos.present?`), it returned false every time for any assignment with a roster. 
This is a pretty simple fix so I think I'm going to go ahead and merge it in so people don't hit the issue over the week
cc @BenEmdon 
Screenshot of an affected assignment with a repository:
> Fix disabled Download Repositories button for assignments with rosters

- app/services/organization_webhook_health_service.rb
- spec/services/organization_webhook_health_service_spec.rb
Adds a progress bar to `OrganizationWebhookHealthService`:
```
➜  rake organization_webhook_health_migration:migrate_all
Iterating over OrganizationWebhooks: Time: 00:00:00 Time: 00:00:00 2/2 (100%) 0 |=============================================================|
Organization Webhook Health Service Results
–––––––––––––––––––––––––––––––––––––––––––
Success count: 2
Errored organization webhooks:
{}
```
> Add a progress bar to OrganizationWebhookHealthService

- app/controllers/organizations_controller.rb
- app/jobs/organization_event_job.rb
- app/models/user.rb
- app/services/transfer_assignments_service.rb
- spec/services/transfer_assignments_service_spec.rb
We had duplicate code for transferring assignments from one admin to other. So, in this PR I have created a service `TransferAssignmentsService` which does the transfer process and is called instead of the duplicate code.
P.S. I discovered this when working on #1864 and hence closing the original PR in favor of this.
> Add new service to transfer assignments, removes duplicate code

- db/migrate/20190618173308_add_max_teams_to_group_assignments.rb
- db/schema.rb
This migration is required for #1876. It adds the `max_teams` column to `GroupAssignments`, allowing teachers to set the maximum amount of teams allowed in a group assignment.
> Migration for max_teams in group assignments

- app/views/assignments/show.html.erb
"assignment" has been misspelled as "assigment" on the assignment page for 2 years 🤔
> Fix spelling mistake in assignment view

- script/test
This PR makes the test script (`script/test`) run the linter script.
It's very easy to forget to run the linter after running the tests. I think we'd all like to catch these linter issues before pushing!
> Add linter to test script

- app/jobs/membership_event_job.rb
- spec/jobs/membership_event_job_spec.rb
Adds a condition in MembershipEventJob to check if repo_access is present before deleting it. This fixes #1898 and will reduce the backlog of retries in `sidekiq`.
> MembershipEventJob: add condition to check if repo_access is present before deleting

- app/models/group_assignment_repo/creator.rb
- app/models/group_assignment_repo/creator/result.rb
- spec/jobs/group_assignment_repo/create_github_repository_job_spec.rb
- spec/models/group_assignment_repo/creator_spec.rb
Second (2/2) part which closes #1684.
This PR adds the detailed GitHub error to the user-friendly (but very uninformative) error messages we're reporting when creating group assignments.
Identical to #1892.
> Better error reporting on group assignment repo creator

- app/controllers/application_controller/feature_flags_dependency.rb
- app/views/assignments/show.html.erb
- app/views/group_assignments/show.html.erb
cc https://github.com/education/classroom/issues/1951
Removes the old `download_repositories` flipper logic.
> Remove download repositories feature flag

- app/models/organization.rb
- spec/models/organization_spec.rb
This PR adds the `has_one` relationship between `organization` and `lti_configuration`.
> Add "has_one" relationship on organization to lti_configuration

- app/models/user.rb
While our ES is down, lets stop trying to index users, it's causing floods of exceptions.
> Stop indexing users for now

- app/controllers/application_controller/feature_flags_dependency.rb
- app/controllers/pages_controller.rb
cc https://github.com/education/classroom/issues/1951
Removes:
- public_assistant_landing_page
- assistant_landing_page
assistand_landing_page is not 100%, but it's also not being used in the codebase. Is this OK @srinjoym ?
> Remove assistant_landing_page and public_assistant_landing_page

- app/assets/stylesheets/components/message-of-the-day.scss
Closes https://github.com/education/classroom/issues/1980
Fixed screenshot:
> Fix message of the day styling error

- app/models/assignment_repo/creator.rb
- app/models/assignment_repo/creator/reporter.rb
- app/models/group_assignment_repo/creator.rb
- app/models/group_assignment_repo/creator/reporter.rb
- spec/jobs/assignment_repo/create_github_repository_job_spec.rb
- spec/models/assignment_repo/creator_spec.rb
This PR adds a metric for the repo creation time when using the source importer.
I'll also add a metric for template repo creation which lets us compare the time/performance difference when using template repos vs the source importer.
> Add stats for repo creation time with importer

- app/views/orgs/rosters/_new_student_modal.html.erb
There was a bug in the initial PR which did not show the sync modal when there was an existing Google Classroom integration. This PR fixes it.
No tests are written as it is very difficult to render the partial and have the google credentials for it.
> When Google Classroom Integration Exists Show Sync Modal

- db/migrate/20190716211230_add_column_to_lti_configurations.rb
- db/schema.rb
Migration to persist the `context_membership_url` to a given `LtiConfiguration`. This url is used for importing the members of an LMS context (e.g. a course or a course section), and is unchanging across LMS launches.
As noted in #1987, It'll be nice to have this url persisted because it will mean that after an instructor's first launch of Classroom from their LMS, they won't have to relaunch it in the future to re-import the roster for their linked course.
> Add context_membership_url to lti_configurations table

- .travis.yml
Closes https://github.com/education/classroom/issues/2059
Removes the 9.4 PG builds since we're using 10 in prod now 🎉
> Remove Postgres 9.4 builds

- app/views/assignments/_assignment_form_options.html.erb
- app/views/group_assignments/_group_assignment_form_options.html.erb
Since template repos in general are very new and we've seen some minor issues, we should note that this feature is a beta using a badge.
> Add beta badge to template repos option

- app/controllers/assignment_invitations_controller.rb
- app/controllers/group_assignment_invitations_controller.rb
- app/jobs/group_assignment_repo/create_github_repository_job.rb
- app/models/assignment_repo/creator.rb
- app/models/assignment_repo/creator/reporter.rb
- app/models/group_assignment_repo/creator.rb
- app/models/group_assignment_repo/creator/reporter.rb
- spec/controllers/assignment_invitations_controller_spec.rb
- spec/controllers/group_assignment_invitations_controller_spec.rb
- spec/jobs/assignment_repo/create_github_repository_job_spec.rb
- spec/jobs/group_assignment_repo/create_github_repository_job_spec.rb
- spec/models/assignment_repo/creator_spec.rb
- spec/models/group_assignment_repo/creator_spec.rb
This pull request removes the `v2` prefix that was added when `import_resiliency` was introduced. Since that feature is now 100% deployed, we remove the `v2` prefix and consider all the stats sent as primary.
__IMPORTANT:__ This affects our graphs in datadog, so we need to update them *before* or *as soon as* this pull request is in production.
> Remove v2 prefix from stats used for repo creation

- app/views/assignments/show.html.erb
- app/views/group_assignments/show.html.erb
Fixes #2093.
We're enabling the "Download Repositories" button based on the `@assignment_repos` variable being present. If we're using rosters, `@assignment_repos` is not defined and we use `@roster_entries` and `@unlinked_user_repos` instead. We shouldn't check these since they're defined for the view (for the search bar it looks like). See here: https://github.com/education/classroom/blob/master/app/controllers/assignments_controller.rb#L35
This change checks if the assignment record has any assignment repositories.
> Fix download repos button

- app/views/organizations/edit.html.erb
Adding a feature flag check for LTI and Google Classroom on the settings page. As this currently shows up for everyone on production.
> Add feature flag check

- app/views/organizations/link_lms.html.erb
Currently, Google Classroom is displayed as "Google Class" which we should not do. So this PR makes it so that we can display the full name. To do that I'm also changing how many LMSs are displayed in one row.
Also updated the text copy!
> Change layout of LMS links

- CODEOWNERS
Right now we only have a few code owners. Now that we have a larger `-reviewers` team we can share the work and get approvals. Also, we can add and remove people from the team externally.
cc @andrewbredow
> Adding the classroom-reviewers team as a code owner

- config/routes.rb
- spec/integration/lti_launch_spec.rb
As identified in #2166, `/auth/lti/launch` should only accept POST requests.
> Cange lti_launch to :post

- app/jobs/assignment/repository_visibility_job.rb
- app/jobs/assignment_repository_visibility_job.rb
- app/models/assignment/editor.rb
- spec/controllers/assignments_controller_spec.rb
- spec/controllers/group_assignments_controller_spec.rb
- spec/jobs/repository_visibility_job_spec.rb
- spec/models/assignment/editor_spec.rb
Currently we have two definitions of the `Assignment` class and this tends to break auto-loading in unexpected ways. This PR renames `Assignment::RepositoryVisibilityJob` to `AssignmentRepositoryVisibilityJob` making it no-longer-nested. This keeps the concerns of Jobs and Models separate.
Because this PR renames a Job we need to deploy the fix in multiple steps:
1. Duplicate the job with the new name and start using that new job only
2. Deploy that change
2. Wait until the old jobs are out of the queue (and only new jobs are being enqueued)
3. Remove the old job and deploy 
This should fix the `Assignment` errors which led to today's maintenance mode.
> Rename Assignment::RepositoryVisibilityJob to a single class

- app/assets/stylesheets/components/message-of-the-day.scss
- app/views/shared/_message_of_the_day.html.erb
Changed the non-standard green link to standard blue; also used standard Primer flash banner  :sparkles:
> fixed green link and used standard flash banner

- docs/generate-lms-credentials.md
- docs/import-roster-from-lms.md
- docs/probot-settings.md
- docs/setup-canvas.md
- docs/setup-generic-lms.md
- docs/setup-moodle.md
- docs/upgrade-your-organization.md
Closes #2247. Fixes the weird centering issues on Safari with images in the docs caused by the `.d-flex` class and replaces them with the `.text-center` class. 
For reasons I could not diagnose even after playing around in the chrome dev tools for far too long ([how I feel rn](https://assets.website-files.com/5c7fdbdd4e3feeee8dd96dd2/5cf55c917b91f817a2be8637_cszhu.png)),  the `.mx-auto` margin-centering does not work, even though the image has a set width. 
Regardless, now support doc images are properly centered on Safari!
> Center support doc images on safari

- app/assets/stylesheets/components/message-of-the-day.scss
- app/views/shared/_message_of_the_day.html.erb
Closes https://github.com/education/classroom/issues/2257
Fixes the MOTD so it is responsive. Uses primer container to fix it.
> Make MOTD responsive

- app/views/assignments/show.html.erb
- app/views/group_assignments/show.html.erb
- app/views/shared/_invitation.html.erb
- app/views/shared/invitations/_clipboard_form.html.erb
- Changed the assignment empty state messaging from “[assignment name] does not have any repositories” to "No students have accepted  [assignment name]." The former message read as though it was prompting the teacher to create a repo or associate the assignment with a starter code repo.
- Added a bit of vertical space between the copy widget and the empty state box since it was sitting on top of it (see Before screenshot).
- Made a few UI tweaks to the URL copy widget:
- Added `.note` to the explanatory text to make it less prominent
- Removed the `Copy invitation link` button label. Since the checkbox label already clearly identifies the URL as an invitation link, the button label was redundant. Teachers are also already familiar with the copy functionality from GitHub's clone/download …
> updated assignment empty state messaging + UI tweaks to URL copy functionality

- docs/using-template-repos-for-assignments.md
Currently, template repos have a file size limit of 10mb. If users try to clone a template repo with a file size >10mb, on classroom it will succeed but the github repo will not clone properly.
> Mention file size limit for templates in docs

- docs/setup-canvas.md
This updates Canvas' help page, to say that we do not support free teacher accounts. This is primarily due to the fact that Canvas does not allow the membership service setting to be turned on for free accounts.
> Update Canvas help page

- app/views/assignments/_assignment_form_options.html.erb
- app/views/group_assignments/_group_assignment_form_options.html.erb
We currently have a giant mess of HTML as our starter code repo field in the assignment forms.
This PR switches it over to the rails form helper format, keeping it consistent, clean, and easier to read.
The form looks/operates exactly the same on the client-side.
> Use form helper instead of HTML for starter code repo field

- app/views/assignments/_assignment_form_options.html.erb
- app/views/group_assignments/_group_assignment_form_options.html.erb
Just noticed that #2290 had the object name for the starter code repo form helper as `:title` when it should've been `:starter_code_repository`. 
https://github.com/education/classroom/pull/2290/files#diff-addecbb36a5dac12ef1fc5440d5048faR59
This doesn't cause any issues, but it's best we change it to the appropriate name.
> Fix object name for starter code repo field in assignment forms

- Gemfile
- Gemfile.lock
- lib/github_classroom/lti/mixins/request_signing.rb
- spec/lib/github_classroom/lti/membership_service_spec.rb
Canvas hosted on Instructure, gzips their response. So this PR allows us to unzip the response, therefore fixing the importing students issue with Canvas 😄
> Adding unzip of gzip responses

- app/assets/stylesheets/application.scss
Closes #2248 
This removes `@import "github-markdown-css/github-markdown.css";` from our `application.scss`.
We use the css provided by this file. However, that CSS is included through npm/yarn and has never been directly in the codebase (which is what is causing the 404 in console).
This clears up the 404 but still leaves the styles available (through the inclusion in npm/yarn).
As you can see from the 3 screenshots below, we definitely have specific styles for `markdown-body` class and removing this line does not prevent us from getting that style info:
How a page using `markdown-body` looks with that line removed locally:
How that same page looks on production (where the line is present):
How that page looks if I remove the `markdown-body` class:
> Remove unnecessary import for github-markdown-css

- app/views/assignments/_assignment_form_options.html.erb
- app/views/assignments/new.html.erb
- app/views/group_assignments/_group_assignment_form_options.html.erb
- app/views/group_assignments/new.html.erb
- app/views/shared/_unlimited_free_private_repositories_banner.html.erb
For https://github.com/education/classroom/issues/2281
This PR removes the "free private repos" notice from the assignment form and moves the link to the radio button for using private repos (only displayed when the classroom's org does not have any available private repos).
Before:
Radio buttons when org has no private repos:
Radio buttons when the org does have private repos:
> move free private repo link to private repo radio button

- lib/github_classroom/lti/membership_service.rb
@spinecone brought up a really good point. We should only be rescuing the `JSON::ParserError` error so that we aren't swallowing other errors.
> Rescue only JSON::ParserError

- app/models/organization.rb
- app/views/organizations/_disabled_organization_select.html.erb
- app/views/organizations/_organization_select.html.erb
- app/views/organizations/new.html.erb
For https://github.com/education/classroom/issues/2337
- Changes the organization title maximum length from 60 to 255 characters (to match the limit on github.com organization profile names)
- Removes the `@` from the organization login on the new classroom form
- Changes the organizations on the new classroom form to be displayed 3 per row rather than 4 per row
- No longer truncating the organization login, which can be up to 40 characters
The new classroom form now looks like this:
> allow longer organization titles and display logins better

- app/assets/stylesheets/layout.scss
- Added padding between the main content and the footer
- Changed the background color to a lighter grey to improve text contrast/readability
> Small visual tweaks

- app/models/lti_configuration.rb
- db/schema.rb
- docs/connect-to-lms.md
We currently do not support Brightspace with LTI 1.0/1.1 as they did not implement IMS names and provisioning service. So we are going to be removing Brightspace, as a supported LMS.
> Remove Brightspace from supported LMSs

- app/controllers/application_controller/feature_flags_dependency.rb
Closes #2349
This adds the `onboarding_redesign_enabled?` feature flag helper method. I've also created the feature flag in devtools so it will be available in production.
This will enable us to easily check if the flag is enabled in future development as we work on the onboarding redesign.
Because onboarding can start before a person is logged in, I've set this up to check for global enablement or enablement for a specific user. This will make local dev easier since you can enable globally in order to get the updated version even if your local user is logged out.
> Add `onboarding_redesign` feature flag helper method

- .rubocop.yml
- app/controllers/application_controller/feature_flags_dependency.rb
- app/controllers/assignment_invitations_controller.rb
- app/controllers/assignments_controller.rb
- app/controllers/concerns/starter_code.rb
- app/controllers/group_assignment_invitations_controller.rb
- app/controllers/group_assignments_controller.rb
- app/controllers/organizations_controller.rb
- app/controllers/orgs/rosters_controller.rb
- app/models/github_organization.rb
- app/models/github_repository.rb
- app/services/create_github_repo_service.rb
- lib/docker_compose/parser.rb
- lib/github_classroom/lti/models/membership_extension/message_response.rb
- spec/lib/github_classroom/lti/membership_service_spec.rb
- spec/models/group_assignment_repo_spec.rb
- spec/models/user_spec.rb
- spec/services/create_github_repo_service_spec.rb
I've seen myself/others get CI failures for exceeding the 120 character line limit a few times, and my preference is to review line length on context rather than a hard rule. We're also disabling these metrics 20 times across the codebase already. I'm open to feedback if folks feel strongly that we should keep these though!
> remove linter rule for line limit

- lib/tasks/enable_features.rake
These three feature flags only appear in this rake task.
I'm removing them as part of a cleanup task to make sure the only feature flags that remain in the codebase are flags for features that are actively under development.
There are some others here that can potentially be removed; however, they also have other code tied to the feature flag so I'll pull them out separately in a PR related to just that feature flag.
> Remove feature flags that only appear in the rake task

- app/views/assignments/show.html.erb
- app/views/group_assignments/_banner.html.erb
- app/views/group_assignments/show.html.erb
- app/views/shared/_deadline_with_local_time.html.erb
For https://github.com/education/classroom/issues/2363
Include the exact deadline on the assignment show page (in current user's local timezone)
It currently looks like this:
We are discussing making further improvements to the time formatting, such as using 24 hour time and including the full month name and the user's timezone in the display.
> convert deadline to local time in assignment display

- app/assets/javascripts/application.js
- app/assets/javascripts/organization-filtering.js
- app/views/organizations/_organization_filters.html.erb
- package.json
- yarn.lock
Previously the search/filter form on the `/classrooms` page was not working in Firefox. It was submitting twice (the first time correctly as an async request and the second time as a full page load).
This updates the `dispatchEvent` for the form submission so it includes `cancelable: true` which prevents the double submission.
There was some additional cleanup work included here:
Eventually, we should replace our custom debounce functions with a standardized implementation. The JS folks recommended https://github.com/github/mini-throttle/. This will be done in a later PR as it will require some larger changes.
> Fix search/filter so it works on Firefox

- app/assets/javascripts/organization-filtering.js
**************** NOTES ****************
This is adding back some of the work that was reverted in #2432 
This includes only the changes related to getting the form to work on Firefox. It does not include the details-menu js change which is what appears to have caused the break.
I've tested form functionality and assignment import functionality on Chrome, Safari, Firefox and Edge with these changes and it is working on all of them.
**************** NOTES ****************
Previously the search/filter form on the /classrooms page was not working in Firefox. It was submitting twice (the first time correctly as an async request and the second time as a full page load).
This updates the dispatchEvent for the form submission so it includes cancelable: true which prevents the double submission. …
> Fix search and filter form on Firefox

- docs/help.md
Changes repo to repository in /help docs per [brand guidelines](https://brand.github.com/content/grammar-usage/)
> changes `repo` to `repository` per brand guidelines

- app/views/organizations/setup.html.erb
- config/locales/views/organizations/en.yml
- db/schema.rb
Small copy changes to help new GitHub Classroom users figure out a good name for their classroom
While observing teachers create new classrooms, I noticed that none of them actually used the classroom name that was auto-generated for them. But new users, in particular, weren't sure what _would_ make a good classroom name. They didn't know whether the name would be visible to students. They weren't sure if they needed to create separate classrooms for different sections of the same course. 
Hopefully, these small copy changes can help address those issues.
> copy changes to help teachers come up with a useful classroom name

- app/views/assignment_invitations/setup.html.erb
- app/views/group_assignment_invitations/setup.html.erb
Fixing typo. `Setup` is a noun but in this context, `set up` the verb form applies.
> fixed small typo setup => set up

- app/views/shared/_header.html.erb
- config/locales/views/shared/en.yml
Adjustment to accommodate longer (8 character +) usernames on the nav menu since it's likely that newer users will have longer usernames. Display follows the menu logged in username pattern on dotcom.
**Before**
**After**
> small adjustment so longer usernames are readable on nav menu

- .gitignore
- Brewfile
It fixes the app setup by removing `caskroom/cask` from `Brewfile`. 
Homebrew Cask is now integrated into Homebrew itself and tapping caskroom/cask is not necessary Homebrew/homebrew-cask#14384
Closes #2515
> Fix script/setup by removing Homebrew cask
